#ifndef	__FTNM_CONFIG_H__
#define	__FTNM_CONFIG_H__

#include "ftm_types.h"
#include "ftm_object.h"
#include "ftm_list.h"
#include "ftdm_client.h"
typedef	struct
{
	FTM_USHORT		usPort;
	FTM_ULONG		ulMaxSession;
}	FTNM_CFG_SERVER, _PTR_ FTNM_CFG_SERVER_PTR;

typedef	struct
{
	FTM_CHAR		pName[1024];
	FTM_LIST		xMIBList;
}	FTNM_CFG_SNMPC, _PTR_ FTNM_CFG_SNMPC_PTR;
	
FTM_RET	FTNM_CFG_SERVER_create(FTNM_CFG_SERVER_PTR _PTR_ ppConfig);
FTM_RET	FTNM_CFG_SERVER_copyCreate(FTNM_CFG_SERVER_PTR _PTR_ ppConfig, FTNM_CFG_SERVER_PTR pOldConfig);
FTM_RET	FTNM_CFG_SERVER_destroy(FTNM_CFG_SERVER_PTR pConfig);

FTM_RET	FTNM_CFG_SERVER_init(FTNM_CFG_SERVER_PTR pConfig);
FTM_RET FTNM_CFG_SERVER_load(FTNM_CFG_SERVER_PTR pConfig, FTM_CHAR_PTR pFileName);
FTM_RET	FTNM_CFG_SERVER_final(FTNM_CFG_SERVER_PTR pConfig);

FTM_RET	FTNM_CFG_SERVER_copy(FTNM_CFG_SERVER_PTR pDestCfg, FTNM_CFG_SERVER_PTR pSrcCfg);

FTM_RET	FTNM_CFG_SERVER_show(FTNM_CFG_SERVER_PTR pConfig);

FTM_RET	FTNM_CFG_DMC_create(FTDMC_CFG_PTR _PTR_ ppConfig);
FTM_RET	FTNM_CFG_DMC_copyCreate(FTDMC_CFG_PTR _PTR_ ppConfig, FTDMC_CFG_PTR pOldConfig);
FTM_RET	FTNM_CFG_DMC_destroy(FTDMC_CFG_PTR pConfig);

FTM_RET	FTNM_CFG_DMC_init(FTDMC_CFG_PTR pConfig);
FTM_RET FTNM_CFG_DMC_load(FTDMC_CFG_PTR pConfig, FTM_CHAR_PTR pFileName);
FTM_RET	FTNM_CFG_DMC_final(FTDMC_CFG_PTR pConfig);

FTM_RET	FTNM_CFG_DMC_copy(FTDMC_CFG_PTR pDestCfg, FTDMC_CFG_PTR pSrcCfg);

FTM_RET	FTNM_CFG_DMC_show(FTDMC_CFG_PTR pConfig);

FTM_RET	FTNM_CFG_SNMPC_create(FTNM_CFG_SNMPC_PTR _PTR_ ppConfig);
FTM_RET	FTNM_CFG_SNMPC_copyCreate(FTNM_CFG_SNMPC_PTR _PTR_ ppConfig, FTNM_CFG_SNMPC_PTR pOldConfig);
FTM_RET	FTNM_CFG_SNMPC_destroy(FTNM_CFG_SNMPC_PTR pConfig);

FTM_RET	FTNM_CFG_SNMPC_init(FTNM_CFG_SNMPC_PTR pConfig);
FTM_RET FTNM_CFG_SNMPC_load(FTNM_CFG_SNMPC_PTR pConfig, FTM_CHAR_PTR pFileName);
FTM_RET	FTNM_CFG_SNMPC_final(FTNM_CFG_SNMPC_PTR pConfig);

FTM_RET	FTNM_CFG_SNMPC_copy(FTNM_CFG_SNMPC_PTR pDestCfg, FTNM_CFG_SNMPC_PTR pSrcCfg);

FTM_RET	FTNM_CFG_SNMPC_show(FTNM_CFG_SNMPC_PTR pConfig);

#endif
