#ifndef	_FTNM_SNMPTRAPD_H_
#define	_FTNM_SNMPTRAPD_H_

#include <pthread.h>
#include "ftm_types.h"

#define	FTNM_SNMPTRAPD_NAME_LENGTH	128
#define	FTNM_SNMPTRAPD_NAME			"ftnm:snmptrapd"
#define	FTNM_SNMPTRAPD_PORT			162

typedef	FTM_RET (*FTNM_SNMPTRAPD_CALLBACK)(FTM_CHAR_PTR pTrapMsg);

typedef struct
{
	FTM_CHAR				pName[FTNM_SNMPTRAPD_NAME_LENGTH + 1];
	FTM_USHORT				usPort;
}	FTNM_SNMPTRAPD_CONFIG, _PTR_ FTNM_SNMPTRAPD_CONFIG_PTR;
	
typedef	struct
{
	FTNM_SNMPTRAPD_CONFIG	xConfig;
	FTNM_SNMPTRAPD_CALLBACK	fTrapCB;
	FTM_BOOL				bRunning;
	pthread_t				xPThread;
}	FTNM_SNMPTRAPD, _PTR_ FTNM_SNMPTRAPD_PTR;

FTM_RET	FTNM_SNMPTRAPD_create(FTNM_SNMPTRAPD_PTR _PTR_ ppCTX);
FTM_RET	FTNM_SNMPTRAPD_destroy(FTNM_SNMPTRAPD_PTR pCTX);

FTM_RET FTNM_SNMPTRAPD_start(FTNM_SNMPTRAPD_PTR pCTX);
FTM_RET FTNM_SNMPTRAPD_stop(FTNM_SNMPTRAPD_PTR pCTX);

FTM_RET FTNM_SNMPTRAPD_loadConfig(FTNM_SNMPTRAPD_PTR pCTX, FTM_CHAR_PTR pFileName);
FTM_RET FTNM_SNMPTRAPD_showConfig(FTNM_SNMPTRAPD_PTR pCTX);

FTM_RET	FTNM_SNMPTRAPD_setTrapCB(FTNM_SNMPTRAPD_PTR pCTX, FTNM_SNMPTRAPD_CALLBACK fTrapCB);
#endif
