#ifndef	_FTNM_PLUGIN_SERVER_H_
#define	_FTNM_PLUGIN_SERVER_H_

#include "ftm_types.h"

FTM_RET	(*FTNM_PLUGIN_INIT)(FTM_VOID_PTR pData);
FTM_RET	(*FTNM_PLUGIN_FINAL)(FTM_VOID_PTR pData);
FTM_RET (*FTNM_PLUGIN_CREATE)(FTM_VOID_PTR _PTR_ pInstance);
FTM_RET (*FTNM_PLUGIN_START)(FTM_VOID_PTR pInstance);
FTM_RET (*FTNM_PLUGIN_STOP)(FTM_VOID_PTR pInstance);

typedef	struct
{
	FTNM_PLUGIN_INIT	fInit;
	FTNM_PLUGIN_FINAL	fFinal;
	FTNM_PLUGIN_CREATE	fCreate;
	FTNM_PLUGIN_START	fStart;
	FTNM_PLUGIN_STOP	fStop;
}	FTNM_PLUGIN_SERVER, _PTR_ FTNM_PLUGIN_SERVER_PTR;

#endif
