#ifndef	__FTNM_NODE_H__
#define	__FTNM_NODE_H__

#include "ftm_types.h"
#include "ftm_object.h"
#include "ftm_list.h"
#include "ftnm_ep.h"
#include <pthread.h>

typedef	FTM_ULONG		FTNM_NODE_STATE;

#define	FTNM_NODE_STATE_CREATED					0x00000001
#define	FTNM_NODE_STATE_INITIALIZED				0x00000002
#define	FTNM_NODE_STATE_SYNCHRONIZED			0x00000003
#define	FTNM_NODE_STATE_PROCESS_INIT			0x00000004
#define	FTNM_NODE_STATE_RUN						0x00000005
#define	FTNM_NODE_STATE_STOP					0x00000006
#define	FTNM_NODE_STATE_RUNNING					0x00000007
#define	FTNM_NODE_STATE_PROCESS_FINISHED		0x00000008
#define	FTNM_NODE_STATE_FINISHED				0x00000009
#define	FTNM_NODE_STATE_ABORT					0x0000000A

#define	FTNM_NODE_STATE_TIMEOUT					0x0000000B
#define	FTNM_NODE_STATE_ERROR					0x0000000C
#define	FTNM_NODE_STATE_COMPLETED				0x0000000D

#define	FTNM_NODE_STATE_CANT_OPEN_SESSION		0x0000000E

typedef	FTM_RET		(*FTNM_NODE_START)(FTNM_NODE_PTR pNode);
typedef	FTM_RET		(*FTNM_NODE_STOP)(FTNM_NODE_PTR pNode);
typedef	FTM_RET		(*FTNM_NODE_GET_EP_DATA)(FTNM_NODE_PTR pNode, FTNM_EP_PTR pEP, FTM_EP_DATA_PTR pData);

typedef	struct FTNM_NODE_STRUCT
{
	FTM_NODE_INFO			xInfo;
	FTM_LIST				xEPList;

	pthread_t				xPThread;
	pthread_mutex_t			xMutexLock;
	FTNM_NODE_STATE			xState;
	FTM_ULONG				ulRetry;
	int64_t					xTimeout;

	FTNM_NODE_START			fStart;
	FTNM_NODE_STOP			fStop;
	FTNM_NODE_GET_EP_DATA	fGetEPData;
}	FTNM_NODE, _PTR_ FTNM_NODE_PTR;

FTM_RET FTNM_NODE_init(void);
FTM_RET FTNM_NODE_final(void);

FTM_RET	FTNM_NODE_create(FTM_NODE_INFO_PTR pInfo, FTNM_NODE_PTR _PTR_ ppNode);
FTM_RET	FTNM_NODE_destroy(FTNM_NODE_PTR	pNode);

FTM_RET FTNM_NODE_get(FTM_CHAR_PTR pDID, FTNM_NODE_PTR _PTR_ ppNode);
FTM_RET FTNM_NODE_getAt(FTM_ULONG ulIndex, FTNM_NODE_PTR _PTR_ ppNode);
FTM_RET	FTNM_NODE_count(FTM_ULONG_PTR pulCount);

FTM_RET	FTNM_NODE_linkEP(FTNM_NODE_PTR pNode, FTNM_EP_PTR pEP);
FTM_RET	FTNM_NODE_unlinkEP(FTNM_NODE_PTR pNode, FTNM_EP_PTR pEP);

FTM_RET	FTNM_NODE_getEPCount(FTNM_NODE_PTR pNode, FTM_ULONG_PTR pulCount);
FTM_RET	FTNM_NODE_getEP(FTNM_NODE_PTR pNode, FTM_EPID xEPID, FTNM_EP_PTR _PTR_ pEP);
FTM_RET	FTNM_NODE_getEPAt(FTNM_NODE_PTR pNode, FTM_ULONG ulIndex, FTNM_EP_PTR _PTR_ pEP);
FTM_RET	FTNM_NODE_getEPData(FTNM_NODE_PTR pNode, FTNM_EP_PTR pEP, FTM_EP_DATA_PTR pData);


FTM_RET	FTNM_NODE_start(FTNM_NODE_PTR pNode);
FTM_RET	FTNM_NODE_stop(FTNM_NODE_PTR pNode);

FTM_CHAR_PTR	FTNM_NODE_stateToStr(FTNM_NODE_STATE xState);

#include "ftnm_node_snmpc.h"

#endif

