#ifndef	__FTNM_PARAMS_H__
#define	__FTNM_PARAMS_H__

#include "ftnm_types.h"
#include "ftnm_server_cmd.h"

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
}	FTNM_REQ_PARAMS, _PTR_ FTNM_REQ_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
}	FTNM_RESP_PARAMS, _PTR_ FTNM_RESP_PARAMS_PTR;

typedef	struct 
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_NODE_INFO		xNodeInfo;
}	FTNM_REQ_NODE_CREATE_PARAMS,	_PTR_ FTNM_REQ_NODE_CREATE_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_CHAR			pDID[FTM_DID_LEN + 1];
}	FTNM_RESP_NODE_CREATE_PARAMS, _PTR_ FTNM_RESP_NODE_CREATE_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
}	FTNM_REQ_NODE_DESTROY_PARAMS, _PTR_ FTNM_REQ_NODE_DESTROY_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
}	FTNM_RESP_NODE_DESTROY_PARAMS, _PTR_ FTNM_RESP_NODE_DESTROY_PARAMS_PTR;

typedef struct	
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
}	FTNM_REQ_NODE_COUNT_PARAMS, _PTR_ FTNM_REQ_NODE_COUNT_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_ULONG			ulCount;
}	FTNM_RESP_NODE_COUNT_PARAMS, _PTR_ FTNM_RESP_NODE_COUNT_PARAMS_PTR;

typedef struct	
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
}	FTNM_REQ_NODE_GET_PARAMS, _PTR_ FTNM_REQ_NODE_GET_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_NODE_INFO		xNodeInfo;
}	FTNM_RESP_NODE_GET_PARAMS, _PTR_ FTNM_RESP_NODE_GET_PARAMS_PTR;

typedef struct	
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
}	FTNM_REQ_NODE_GET_AT_PARAMS, _PTR_ FTNM_REQ_NODE_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_NODE_INFO		xNodeInfo;
}	FTNM_RESP_NODE_GET_AT_PARAMS, _PTR_ FTNM_RESP_NODE_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EP_INFO     	xInfo;
}	FTNM_REQ_EP_CREATE_PARAMS, _PTR_ FTNM_REQ_EP_CREATE_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
}	FTNM_RESP_EP_CREATE_PARAMS, _PTR_	FTNM_RESP_EP_CREATE_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EPID 			xEPID;
}	FTNM_REQ_EP_DESTROY_PARAMS, _PTR_	FTNM_REQ_EP_DESTROY_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
}	FTNM_RESP_EP_DESTROY_PARAMS, _PTR_ 	FTNM_RESP_EP_DESTROY_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EP_CLASS		xClass;
}	FTNM_REQ_EP_COUNT_PARAMS, _PTR_ 	FTNM_REQ_EP_COUNT_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_ULONG			nCount;
}	FTNM_RESP_EP_COUNT_PARAMS, _PTR_	FTNM_RESP_EP_COUNT_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EP_CLASS		xClass;
	FTM_ULONG			ulMaxCount;
}	FTNM_REQ_EP_GET_LIST_PARAMS, _PTR_ 	FTNM_REQ_EP_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_ULONG			ulCount;
	FTM_EPID			pEPIDList[];
}	FTNM_RESP_EP_GET_LIST_PARAMS, _PTR_	FTNM_RESP_EP_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EPID			xEPID;
}	FTNM_REQ_EP_GET_PARAMS, _PTR_ 	FTNM_REQ_EP_GET_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_EP_INFO			xInfo;
}	FTNM_RESP_EP_GET_PARAMS, _PTR_	FTNM_RESP_EP_GET_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
}	FTNM_REQ_EP_GET_AT_PARAMS, _PTR_	FTNM_REQ_EP_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_EP_INFO			xInfo;
}	FTNM_RESP_EP_GET_AT_PARAMS, _PTR_	FTNM_RESP_EP_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			nLen;
	FTM_EPID			xEPID;
	FTM_EP_DATA			xData;
}	FTNM_REQ_EP_DATA_ADD_PARAMS, _PTR_ FTNM_REQ_EP_DATA_ADD_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			nLen;
	FTM_RET				nRet;
}	FTNM_RESP_EP_DATA_ADD_PARAMS, _PTR_	FTNM_RESP_EP_DATA_ADD_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EPID			xEPID;
}	FTNM_REQ_EP_DATA_GET_LAST_PARAMS, _PTR_	FTNM_REQ_EP_DATA_GET_LAST_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_EP_DATA 		xData;
}	FTNM_RESP_EP_DATA_GET_LAST_PARAMS, _PTR_ FTNM_RESP_EP_DATA_GET_LAST_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EPID			xEPID;
	FTM_ULONG			nStartIndex;
	FTM_ULONG			nCount; 
}	FTNM_REQ_EP_DATA_GET_LIST_PARAMS, _PTR_	FTNM_REQ_EP_DATA_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			nLen;
	FTM_RET				nRet;
	FTM_ULONG			nCount; 
	FTM_EP_DATA 		pData[];
}	FTNM_RESP_EP_DATA_GET_LIST_PARAMS, _PTR_ FTNM_RESP_EP_DATA_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			nLen;
	FTM_EPID			xEPID;
	FTM_ULONG 			nIndex; 
	FTM_ULONG			nCount;
}	FTNM_REQ_EP_DATA_DEL_PARAMS, _PTR_ FTNM_REQ_EP_DATA_DEL_PARAMS_PTR; 

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			nLen;
	FTM_RET				nRet;
}	FTNM_RESP_EP_DATA_DEL_PARAMS, _PTR_ 	FTNM_RESP_EP_DATA_DEL_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EPID			xEPID;
}	FTNM_REQ_EP_DATA_COUNT_PARAMS, _PTR_ FTNM_REQ_EP_DATA_COUNT_PARAMS_PTR;

typedef	struct
{
	FTNM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				nRet;
	FTM_ULONG			ulCount;
}	FTNM_RESP_EP_DATA_COUNT_PARAMS, _PTR_ FTNM_RESP_EP_DATA_COUNT_PARAMS_PTR;

#endif
