#ifndef	__FTNM_DMC_H__
#define	__FTNM_DMC_H__

#include "ftm.h"
#include "ftdm_client.h"

typedef	struct
{
	pthread_t		xThread;
	FTDMC_SESSION	xSession;
	FTDMC_CFG		xConfig;
}	FTNM_DMC, _PTR_	FTNM_DMC_PTR;

FTM_RET FTNM_DMC_init(FTNM_DMC_PTR pDMC);
FTM_RET FTNM_DMC_final(FTNM_DMC_PTR pDMC);
FTM_RET FTNM_DMC_loadConfig(FTNM_DMC_PTR pDMC, FTM_CHAR_PTR pConfigFileName);

FTM_RET	FTNM_DMC_CFG_create(FTDMC_CFG_PTR _PTR_ ppConfig);
FTM_RET	FTNM_DMC_CFG_copyCreate(FTDMC_CFG_PTR _PTR_ ppConfig, FTDMC_CFG_PTR pOldConfig);
FTM_RET	FTNM_DMC_CFG_destroy(FTDMC_CFG_PTR pConfig);

FTM_RET	FTNM_DMC_CFG_init(FTDMC_CFG_PTR pConfig);
FTM_RET FTNM_DMC_CFG_load(FTDMC_CFG_PTR pConfig, FTM_CHAR_PTR pFileName);
FTM_RET	FTNM_DMC_CFG_final(FTDMC_CFG_PTR pConfig);

FTM_RET	FTNM_DMC_CFG_copy(FTDMC_CFG_PTR pDestCfg, FTDMC_CFG_PTR pSrcCfg);

FTM_RET	FTNM_DMC_CFG_show(FTDMC_CFG_PTR pConfig);

FTM_RET	FTNM_DMC_EP_DATA_set(FTNM_DMC_PTR pDMC, FTM_EPID xEPID, FTM_EP_DATA_PTR pData);
FTM_RET FTNM_DMC_EP_DATA_setINT(FTNM_DMC_PTR pDMC, FTM_EPID xEPID, FTM_ULONG ulTime, FTM_INT nValue);
FTM_RET FTNM_DMC_EP_DATA_setULONG(FTNM_DMC_PTR pDMC, FTM_EPID xEPID, FTM_ULONG ulTime, FTM_ULONG ulValue);
FTM_RET FTNM_DMC_EP_DATA_setFLOAT(FTNM_DMC_PTR pDMC, FTM_EPID xEPID, FTM_ULONG ulTime, FTM_DOUBLE fValue);
FTM_RET	FTNM_DMC_EP_DATA_count(FTNM_DMC_PTR pDMC, FTM_EPID xEPID, FTM_ULONG_PTR pulCount);
FTM_RET	FTNM_DMC_EP_DATA_info(FTNM_DMC_PTR pDMC, FTM_EPID xEPID, FTM_ULONG_PTR pulBeginTime, FTM_ULONG_PTR pulEndTime, FTM_ULONG_PTR pulCount);
#endif

