#ifndef	__FTNM_DMC_H__
#define	__FTNM_DMC_H__

#include "ftm.h"
#include "ftdm_client.h"

FTM_RET FTNM_DMC_init(void);
FTM_RET FTNM_DMC_final(void);

FTM_RET FTNM_DMC_loadConfig(FTM_CHAR_PTR pConfigFileName);
FTM_RET	FTNM_DMC_showConfig(void);

FTM_RET	FTNM_DMC_connect(FTDMC_SESSION_PTR pSession);

FTM_RET	FTNM_DMC_EP_DATA_set(FTDMC_SESSION_PTR pSession, FTM_EP_ID xEPID, FTM_EP_DATA_PTR pData);
FTM_RET FTNM_DMC_EP_DATA_setINT(FTDMC_SESSION_PTR pSession, FTM_EP_ID xEPID, FTM_ULONG ulTime, FTM_INT nValue);
FTM_RET FTNM_DMC_EP_DATA_setULONG(FTDMC_SESSION_PTR pSession, FTM_EP_ID xEPID, FTM_ULONG ulTime, FTM_ULONG ulValue);
FTM_RET FTNM_DMC_EP_DATA_setFLOAT(FTDMC_SESSION_PTR pSession, FTM_EP_ID xEPID, FTM_ULONG ulTime, FTM_DOUBLE fValue);
FTM_RET	FTNM_DMC_EP_DATA_count(FTDMC_SESSION_PTR pSession, FTM_EP_ID xEPID, FTM_ULONG_PTR pulCount);
FTM_RET	FTNM_DMC_EP_DATA_info(FTDMC_SESSION_PTR pSession, FTM_EP_ID xEPID, FTM_ULONG_PTR pulBeginTime, FTM_ULONG_PTR pulEndTime, FTM_ULONG_PTR pulCount);
#endif

