#ifndef	__FTNM_SERVER_H__
#define	__FTNM_SERVER_H__

typedef	FTM_RET	(*FTNM_SERVICE_CALLBACK)(FTNM_REQ_PARAMS_PTR, FTNM_RESP_PARAMS_PTR);

typedef struct
{
	FTNM_CMD				xCmd;
	FTM_CHAR_PTR			pCmdString;
	FTNM_SERVICE_CALLBACK	fService;
}	FTNMS_CMD_SET, _PTR_ FTNMS_CMD_SET_PTR;

FTM_RET	FTNMS_run
(
	FTNM_CFG_SERVER_PTR 	pConfig,
	pthread_t 				*pPThread 
);

FTM_RET	FTNMS_serviceCall
(
	FTNM_REQ_PARAMS_PTR		pReq,
	FTNM_RESP_PARAMS_PTR	pResp
);

FTM_RET	FTNMS_NODE_create
(
	FTNM_REQ_NODE_CREATE_PARAMS_PTR		pReq,
	FTNM_RESP_NODE_CREATE_PARAMS_PTR	pResp
);

FTM_RET	FTNMS_NODE_destroy
(
	FTNM_REQ_NODE_DESTROY_PARAMS_PTR	pReq,
	FTNM_RESP_NODE_DESTROY_PARAMS_PTR	presp
);

FTM_RET	FTNMS_NODE_count
(
 	FTNM_REQ_NODE_COUNT_PARAMS_PTR		pReq,
	FTNM_RESP_NODE_COUNT_PARAMS_PTR		pResp
);

FTM_RET	FTNMS_NODE_get
(
 	FTNM_REQ_NODE_GET_PARAMS_PTR		pReq,
	FTNM_RESP_NODE_GET_PARAMS_PTR		pResp
);

FTM_RET	FTNMS_NODE_getAt
(
 	FTNM_REQ_NODE_GET_AT_PARAMS_PTR		pReq,
	FTNM_RESP_NODE_GET_AT_PARAMS_PTR	pResp
);

FTM_RET	FTNMS_EP_create
(
 	FTNM_REQ_EP_CREATE_PARAMS_PTR		pReq,
	FTNM_RESP_EP_CREATE_PARAMS_PTR		pResp
);

FTM_RET	FTNMS_EP_destroy
(
 	FTNM_REQ_EP_DESTROY_PARAMS_PTR		pReq,
	FTNM_RESP_EP_DESTROY_PARAMS_PTR		pResp
);

FTM_RET	FTNMS_EP_count
(
 	FTNM_REQ_EP_COUNT_PARAMS_PTR		pReq,
	FTNM_RESP_EP_COUNT_PARAMS_PTR		pResp
);

FTM_RET	FTNMS_EP_getList
(
 	FTNM_REQ_EP_GET_LIST_PARAMS_PTR		pReq,
	FTNM_RESP_EP_GET_LIST_PARAMS_PTR	pResp
);

FTM_RET	FTNMS_EP_get
(
 	FTNM_REQ_EP_GET_PARAMS_PTR		pReq,
	FTNM_RESP_EP_GET_PARAMS_PTR		pResp
);

FTM_RET	FTNMS_EP_getAt
(
 	FTNM_REQ_EP_GET_AT_PARAMS_PTR	pReq,
	FTNM_RESP_EP_GET_AT_PARAMS_PTR	pResp
);

#endif
