#ifndef	_FTM_SERVICE_H_
#define	_FTM_SERVICE_H_

#include "ftm.h"
#include "ftnm_msg.h"

typedef	enum
{
	FTNM_SERVICE_ALL = 0,
	FTNM_SERVICE_SERVER,
	FTNM_SERVICE_SNMP_CLIENT,
	FTNM_SERVICE_SNMPTRAPD,
	FTNM_SERVICE_DBM,
}	FTNM_SERVICE_TYPE, _PTR_ FTNM_SERVICE_TYPE_PTR;

typedef	FTM_ULONG	FTNM_SERVICE_ID;

typedef	FTM_RET	(*FTNM_SERVICE_INIT)(FTM_VOID_PTR pData);
typedef	FTM_RET	(*FTNM_SERVICE_FINAL)(FTM_VOID_PTR pData);
typedef	FTM_RET	(*FTNM_SERVICE_START)(FTM_VOID_PTR pData);
typedef	FTM_RET	(*FTNM_SERVICE_STOP)(FTM_VOID_PTR pData);
typedef	FTM_RET	(*FTNM_SERVICE_CALLBACK)(FTNM_SERVICE_ID xID, FTNM_MSG_TYPE xMsg, FTM_VOID_PTR pData);
typedef	FTM_RET	(*FTNM_SERVICE_SET_CALLBACK)(FTM_VOID_PTR pData, FTNM_SERVICE_ID xID, FTNM_SERVICE_CALLBACK fCB);
typedef	FTM_RET	(*FTNM_SERVICE_LOAD_FROM_FILE)(FTM_VOID_PTR pData, FTM_CHAR_PTR pFileName);
typedef	FTM_RET	(*FTNM_SERVICE_SHOW_CONFIG)(FTM_VOID_PTR pData);
typedef	FTM_RET	(*FTNM_SERVICE_NOTIFY)(FTM_VOID_PTR pData, FTNM_MSG_PTR pMsg);

typedef	struct
{
	FTNM_SERVICE_TYPE			xType;
	FTNM_SERVICE_ID				xID;
	FTM_CHAR_PTR				pName;
	FTNM_SERVICE_INIT			fInit;
	FTNM_SERVICE_FINAL			fFinal;
	FTNM_SERVICE_START			fStart;
	FTNM_SERVICE_STOP			fStop;
	FTNM_SERVICE_SET_CALLBACK	fSetCallback;
	FTNM_SERVICE_CALLBACK		fCallback;
	FTNM_SERVICE_LOAD_FROM_FILE	fLoadFromFile;
	FTNM_SERVICE_SHOW_CONFIG	fShowConfig;
	FTNM_SERVICE_NOTIFY			fNotify;

	FTM_VOID_PTR				pData;

// Run-time data
	FTM_RET						xRet;
}	FTNM_SERVICE, _PTR_ FTNM_SERVICE_PTR;

FTM_RET	FTNM_SERVICE_init(FTNM_SERVICE_PTR pServices, FTM_ULONG ulCount);
FTM_RET	FTNM_SERVICE_final(FTM_VOID);

FTM_RET	FTNM_SERVICE_loadFromFile(FTNM_SERVICE_TYPE xType, FTM_CHAR_PTR pFileName);
FTM_RET	FTNM_SERVICE_showConfig(FTNM_SERVICE_TYPE xType);
FTM_RET	FTNM_SERVICE_start(FTNM_SERVICE_TYPE xType);
FTM_RET	FTNM_SERVICE_stop(FTNM_SERVICE_TYPE xType);
FTM_RET	FTNM_SERVICE_notify(FTNM_SERVICE_TYPE xType, FTNM_MSG_PTR pMsg);

FTM_RET	FTNM_SERVICE_register(FTNM_SERVICE_PTR pService);
FTM_RET	FTNM_SERVICE_unregister(FTNM_SERVICE_TYPE xType);

FTM_RET FTNM_SERVICE_count(FTM_ULONG_PTR pulCount);
FTM_RET FTNM_SERVICE_get(FTNM_SERVICE_TYPE xType, FTNM_SERVICE_PTR _PTR_ ppService);
FTM_RET FTNM_SERVICE_getAt(FTM_ULONG ulIndex, FTNM_SERVICE_PTR _PTR_ ppService);


#endif
