#ifndef	_FTM_CONFIG_H_
#define	_FTM_CONFIG_H_

#include "ftm_types.h"
#include "libconfig.h"
#include "ftm_node.h"
#include "ftm_ep.h"
#include "ftm_time.h"

typedef	struct
{
	config_t		xLibConfig;
}	FTM_CONFIG, _PTR_ FTM_CONFIG_PTR;

typedef	struct
{
	config_setting_t	*pSetting;
}	FTM_CONFIG_ITEM, _PTR_ FTM_CONFIG_ITEM_PTR;

FTM_RET	FTM_CONFIG_create
(
	FTM_CHAR_PTR 		pFileName, 
	FTM_CONFIG_PTR _PTR_ pConfig
);

FTM_RET	FTM_CONFIG_destroy
(
	FTM_CONFIG_PTR 		pConfig
);

FTM_RET	FTM_CONFIG_init
(
	FTM_CONFIG_PTR 		pConfig, 
	FTM_CHAR_PTR 		pFileName
);

FTM_RET	FTM_CONFIG_final
(
	FTM_CONFIG_PTR 		pConfig
);

FTM_RET	FTM_CONFIG_getItem
(
	FTM_CONFIG_PTR 		pConfig, 
	FTM_CHAR_PTR 		pName, 
	FTM_CONFIG_ITEM_PTR pItem
);

FTM_RET	FTM_CONFIG_LIST_getItemCount
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG_PTR pulCount
);

FTM_RET	FTM_CONFIG_LIST_getItemAt
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG 			ulIndex, 
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_ITEM_create
(
	FTM_CONFIG_ITEM_PTR _PTR_ ppItem
);

FTM_RET	FTM_CONFIG_ITEM_destroy
(
	FTM_CONFIG_ITEM_PTR pItem
);

FTM_RET	FTM_CONFIG_ITEM_getChildItem
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_ITEM_getItemAt
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG 			ulIndex, 
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_ITEM_getItemBOOL
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_BOOL_PTR 		pbValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemUSHORT
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_USHORT_PTR 		pusValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemINT
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_INT_PTR 		pnValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemULONG
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_ULONG_PTR 		pulValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemFLOAT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_FLOAT_PTR 		pfValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemString
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_CHAR_PTR 		pBuff, 
	FTM_ULONG 			ulBuffLen
);

FTM_RET	FTM_CONFIG_ITEM_getItemNode
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_NODE_PTR 		pNode
);

FTM_RET	FTM_CONFIG_ITEM_getItemEP
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_EP_DATA_PTR 	pData
);

FTM_RET	FTM_CONFIG_ITEM_getItemTime
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_TIME_PTR 		pTime
);

FTM_RET	FTM_CONFIG_ITEM_getItemEPData
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_EP_DATA_PTR 	pData
);

FTM_RET	FTM_CONFIG_ITEM_getItemEPClass
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_EP_CLASS_PTR	pEPClass
);

FTM_RET	FTM_CONFIG_ITEM_getBOOL
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_BOOL_PTR pbValue
);

FTM_RET	FTM_CONFIG_ITEM_getUSHORT
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_USHORT_PTR pusValue
);

FTM_RET	FTM_CONFIG_ITEM_getINT
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_INT_PTR 		pnValue
);

FTM_RET	FTM_CONFIG_ITEM_getULONG
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG_PTR 		pulValue
);

FTM_RET	FTM_CONFIG_ITEM_getFLOAT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_FLOAT_PTR 		pfValue
);

FTM_RET	FTM_CONFIG_ITEM_getString
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pBuff, 
	FTM_ULONG 			ulBuffLen
);

FTM_RET	FTM_CONFIG_ITEM_getTime
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_TIME_PTR 		pTime
);

FTM_RET	FTM_CONFIG_ITEM_getNode
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_NODE_PTR 		pNode
);

FTM_RET	FTM_CONFIG_ITEM_getEP
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_EP_PTR 			pEP
);

FTM_RET	FTM_CONFIG_ITEM_getEPData
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_EP_DATA_PTR 	pData
);

FTM_RET FTM_CONFIG_ITEM_getEPClass
(	
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_EP_CLASS_PTR 	pClass
);

FTM_RET	FTM_CONFIG_ITEM_getSNMP
(
	FTM_CONFIG_ITEM_PTR	pItem, 	
	FTM_NODE_OPT_SNMP_PTR 	pSNMP
);
#endif
