#ifndef	__FTOM_BLOCKER_SERVICE_INTERFACE_H__
#define	__FTOM_BLOCKER_SERVICE_INTERFACE_H__

#include "ftm_sim.h"
#include "ftm_sic.h"
#include "ftom_blocker.h"

#define	FTM_SIM_TYPE_BLOCKER_GET_CONFIG		0x01000001

typedef	struct	FTOM_BLOCKER_SIM_REQ_GET_CONFIG_STRCUT
{
	FTM_SIM_REQ	xCommon;
} FTOM_BLOCKER_SIM_REQ_GET_CONFIG, _PTR_ FTOM_BLOCKER_SIM_REQ_GET_CONFIG_PTR;

typedef	struct	FTOM_BLOCKER_SIM_RESP_GET_CONFIG_STRCUT
{
	FTM_SIM_RESP	xCommon;
	FTOM_BLOCKER_CONFIG	xConfig;
} FTOM_BLOCKER_SIM_RESP_GET_CONFIG, _PTR_ FTOM_BLOCKER_SIM_RESP_GET_CONFIG_PTR;

extern	FTM_SIS_CMD	pSISCmdSet[];
extern	FTM_ULONG	ulSISCmdSetCount;

FTM_RET	FTOM_BLOCKER_SIC_getConfig
(
	FTM_SIC_PTR	pSIC,
	FTOM_BLOCKER_CONFIG_PTR	pConfig
);

#endif
