#ifndef	_FTOM_CLOUD_CLIENT_H_
#define	_FTOM_CLOUD_CLIENT_H_


#include "ftom.h"

typedef	FTOM_VOID _PTR_	FTOM_COULD_CLIENT_PTR;
typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CREATE)
(
	FTOM_CLOUD_CLIENT_PTR _PTR_ ppClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_DESTROY)
(
	FTOM_CLOUD_CLIENT_PTR _PTR_ ppClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_INIT)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_FINAL)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_START)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_STOP)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_IS_RUNNING)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_BOOL_PTR			pIsRunning
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_WAITING_FOR_FINISHED)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CONFIG_LOAD)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CONFIG_PTR			pConfig
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CONFIG_SAVE)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CONFIG_PTR			pConfig
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CONFIG_SHOW)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);


typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_SET_NOTIFY_CB)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTOM_CLIENT_NOTIFY_CB	fNotifyCB,
	FTM_VOID_PTR			pData
);

typedef	FTM_RET (*FTOM_CLOUD_CLIENT_MESSAGE_SEND)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTOM_MSG_PTR			pBaseMsg
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_MESSAGE_PROCESS)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTOM_MSG_PTR			pmsg
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CONNECT)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);


typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_TRACE)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_BOOL				bTraceON
);

#endif

