#ifndef	__FTDM_CLIENT_H__
#define	__FTDM_CLIENT_H__

#include "ftdm_types.h"
#include "ftdm_cmd.h"
#include "ftdm_params.h"

typedef struct FTDM_CLIENT_STRUCT _PTR_ FTDM_CLIENT_PTR;


FTM_RET	FTDM_CLIENT_create
(
	FTDM_CLIENT_PTR _PTR_ ppClient
);

FTM_RET	FTDM_CLIENT_destroy
(
	FTDM_CLIENT_PTR _PTR_ ppClient
);

FTM_RET FTDM_CLIENT_connect
(
	FTDM_CLIENT_PTR pClient,
	FTM_IP_ADDR		xIP,
	FTM_USHORT 		usPort 
);

FTM_RET FTDM_CLIENT_disconnect
(
	FTDM_CLIENT_PTR	pClient
);

FTM_RET FTDM_CLIENT_isConnected
(
	FTDM_CLIENT_PTR	pClient,
	FTM_BOOL_PTR	pbConnected
);

FTM_RET FTDM_CLIENT_NODE_append
(
	FTDM_CLIENT_PTR	pClient,
	FTM_NODE_PTR	pInfo
);

FTM_RET FTDM_CLIENT_NODE_remove
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pDID
);

FTM_RET FTDM_CLIENT_NODE_count
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG_PTR	pnCount
);

FTM_RET FTDM_CLIENT_NODE_getAt
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG		ulIndex,
	FTM_NODE_PTR	pNode
);

FTM_RET FTDM_CLIENT_NODE_get
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pDID,
	FTM_NODE_PTR	pNode
);

FTM_RET FTDM_CLIENT_NODE_set
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pDID,
	FTM_NODE_FIELD	xFields,
	FTM_NODE_PTR	pNode
);

FTM_RET	FTDM_CLIENT_NODE_getDIDList
(	
	FTDM_CLIENT_PTR	pClient,
	FTM_DID_PTR		pDIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET FTDM_CLIENT_EP_append
(
	FTDM_CLIENT_PTR	pClient,
	FTM_EP_PTR				pEP
);

FTM_RET FTDM_CLIENT_EP_remove
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR			pEPID
);

FTM_RET FTDM_CLIENT_EP_count
(
	FTDM_CLIENT_PTR	pClient,
	FTM_EP_TYPE		xType,
	FTM_ULONG_PTR	pnCount
);

FTM_RET FTDM_CLIENT_EP_get
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_EP_PTR		pEP
);

FTM_RET FTDM_CLIENT_EP_getAt
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG		ulIndex,
	FTM_EP_PTR		pEP
);

FTM_RET	FTDM_CLIENT_EP_set
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_NODE_FIELD	xFields,
	FTM_EP_PTR		pEP
);

FTM_RET	FTDM_CLIENT_EP_getEPIDList
(	
	FTDM_CLIENT_PTR	pClient,
	FTM_EPID_PTR	pEPIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_CLIENT_EP_CLASS_count
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG_PTR	pnCount
);

FTM_RET	FTDM_CLIENT_EP_CLASS_get
(
	FTDM_CLIENT_PTR	pClient,
	FTM_EP_TYPE		xType,
	FTM_EP_CLASS_PTR	pEPClass
);

FTM_RET	FTDM_CLIENT_EP_CLASS_getAt
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG		ulIndex,
	FTM_EP_CLASS_PTR	pEPClass
);

FTM_RET FTDM_CLIENT_EP_DATA_append
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_EP_DATA_PTR	pData
);

FTM_RET FTDM_CLIENT_EP_DATA_remove
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		ulIndex,
	FTM_ULONG		nCount,
	FTM_ULONG_PTR	pulDeletedCount
);

FTM_RET FTDM_CLIENT_EP_DATA_get
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		nStartIndex,
	FTM_EP_DATA_PTR	pData,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pnCount,
	FTM_BOOL_PTR	pbRemain
);

FTM_RET	FTDM_CLIENT_EP_DATA_removeWithTime
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		nBeginTime,
	FTM_ULONG		nEndTime,
	FTM_ULONG_PTR	pulCount
);

FTM_RET FTDM_CLIENT_EP_DATA_info
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG_PTR	pulBeginTime,
	FTM_ULONG_PTR	pulEndTime,
	FTM_ULONG_PTR	pulCount
);

FTM_RET FTDM_CLIENT_EP_DATA_setLimit
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_EP_LIMIT_PTR	pLimit
);

FTM_RET FTDM_CLIENT_EP_DATA_getWithTime
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		ulBeginTime,
	FTM_ULONG		ulEndTime,
	FTM_BOOL		bAscending,
	FTM_EP_DATA_PTR	pData,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pnCount,
	FTM_BOOL_PTR	pbRemain
);

FTM_RET	FTDM_CLIENT_EP_DATA_count
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG_PTR	pCount
);

FTM_RET	FTDM_CLIENT_EP_DATA_countWithTime
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		ulBeginTime,
	FTM_ULONG		ulEndTime,
	FTM_ULONG_PTR	pCount
);

FTM_RET	FTDM_CLIENT_EVENT_add
(
	FTDM_CLIENT_PTR	pClient,
	FTM_EVENT_PTR   pEvent
);

FTM_RET	FTDM_CLIENT_EVENT_del
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEventID
);

FTM_RET	FTDM_CLIENT_EVENT_count
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_CLIENT_EVENT_get
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEventID,
	FTM_EVENT_PTR	pEvent
);

FTM_RET	FTDM_CLIENT_EVENT_getAt
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG		ulIndex,
	FTM_EVENT_PTR	pEvent
);

FTM_RET	FTDM_CLIENT_EVENT_set
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pEventID,
	FTM_EVENT_FIELD	xFields,
	FTM_EVENT_PTR	pEvent
);

FTM_RET	FTDM_CLIENT_EVENT_getIDList
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ID_PTR		pIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_CLIENT_ACTION_add
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ACTION_PTR 	pAction
);

FTM_RET	FTDM_CLIENT_ACTION_del
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pActionID
);

FTM_RET	FTDM_CLIENT_ACTION_count
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_CLIENT_ACTION_get
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pActionID,
	FTM_ACTION_PTR	pAction
);

FTM_RET	FTDM_CLIENT_ACTION_getAt
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG		ulIndex,
	FTM_ACTION_PTR	pAction
);

FTM_RET	FTDM_CLIENT_ACTION_set
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pActionID,
	FTM_ACTION_FIELD	xFields,
	FTM_ACTION_PTR	pInfo
);

FTM_RET	FTDM_CLIENT_ACTION_getIDList
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ID_PTR		pIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_CLIENT_RULE_add
(
	FTDM_CLIENT_PTR	pClient,
	FTM_RULE_PTR    pRule
);

FTM_RET	FTDM_CLIENT_RULE_del
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pRuleID
);

FTM_RET	FTDM_CLIENT_RULE_count
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_CLIENT_RULE_get
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pRuleID,
	FTM_RULE_PTR	pRule
);

FTM_RET	FTDM_CLIENT_RULE_getAt
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG		ulIndex,
	FTM_RULE_PTR	pRule
);

FTM_RET	FTDM_CLIENT_RULE_set
(
	FTDM_CLIENT_PTR	pClient,
	FTM_CHAR_PTR	pRuleID,
	FTM_RULE_FIELD	xFields,
	FTM_RULE_PTR	pInfo
);

FTM_RET	FTDM_CLIENT_RULE_getIDList
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ID_PTR		pIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);


FTM_RET	FTDM_CLIENT_LOG_add
(
	FTDM_CLIENT_PTR	pClient,
	FTM_LOG_PTR     pLog
);

FTM_RET	FTDM_CLIENT_LOG_del
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulCount,
	FTM_ULONG_PTR	pulDeletedCount
);

FTM_RET	FTDM_CLIENT_LOG_count
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_CLIENT_LOG_get
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulCount,
	FTM_LOG_PTR		pLogs,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_CLIENT_LOG_getAt
(
	FTDM_CLIENT_PTR	pClient,
	FTM_ULONG		ulIndex,
	FTM_LOG_PTR		pLog
);
#endif

