#ifndef	_FTDM_ACTION_H_
#define	_FTDM_ACTION_H_

#include "ftm.h"

typedef	struct
{
	FTM_ACTION	xInfo;
	FTM_ULONG	ulIndex;
}	FTDM_ACTION, _PTR_ FTDM_ACTION_PTR;

FTM_RET	FTDM_ACTION_init
(
	FTDM_CONTEXT_PTR	pFTDM
);

FTM_RET FTDM_ACTION_final
(
	FTDM_CONTEXT_PTR	pFTDM
);

FTM_RET	FTDM_ACTION_showList
(
	FTDM_CONTEXT_PTR	pFTDM
);

FTM_RET	FTDM_ACTION_loadConfig
(
	FTDM_CONTEXT_PTR	pFTDM,
	FTM_CONFIG_PTR		pConfig
);

FTM_RET	FTDM_ACTION_loadFromFile
(
	FTDM_CONTEXT_PTR	pFTDM,
	FTM_CHAR_PTR pFileName
);

FTM_RET	FTDM_ACTION_loadFromDB
(
	FTDM_CONTEXT_PTR	pFTDM
);

FTM_RET	FTDM_ACTION_saveToDB
(
	FTDM_CONTEXT_PTR	pFTDM
);

FTM_RET	FTDM_ACTION_create
(
	FTDM_CONTEXT_PTR	pFTDM,
	FTM_ACTION_PTR pInfo,
	FTDM_ACTION_PTR	_PTR_ ppAction
);

FTM_RET	FTDM_ACTION_destroy
(
	FTDM_CONTEXT_PTR	pFTDM,
	FTM_CHAR_PTR	pActionID
);

FTM_RET	FTDM_ACTION_count
(
	FTDM_CONTEXT_PTR	pFTDM,
	FTM_ULONG_PTR	pnCount
);

FTM_RET	FTDM_ACTION_get
(
	FTDM_CONTEXT_PTR	pFTDM,
	FTM_CHAR_PTR			pActionID,
	FTDM_ACTION_PTR _PTR_ 	ppAction
);

FTM_RET	FTDM_ACTION_getAt
(
	FTDM_CONTEXT_PTR	pFTDM,
	FTM_ULONG		nIndex, 
	FTDM_ACTION_PTR _PTR_	ppAction
);

FTM_RET	FTDM_ACTION_getByIndex
(
	FTDM_CONTEXT_PTR	pFTDM,
	FTM_ULONG				ulIndex,
	FTDM_ACTION_PTR _PTR_ 	ppAction
);

FTM_RET	FTDM_ACTION_getIDList
(
	FTDM_CONTEXT_PTR	pFTDM,
	FTM_ID_PTR		pIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

#endif
