#ifndef	__SQLITE_IF_H__
#define	__SQLITE_IF_H__

#include "ftm_types.h"
#include "ftm_trigger.h"
#include "ftdm_config.h"
#include <sqlite3.h>

typedef	struct FTDM_DBIF_STRUCT
{
	sqlite3	_PTR_ pSQLiteDB;
}	FTDM_DBIF, _PTR_ FTDM_DBIF_PTR;

FTM_RET	FTDM_DBIF_init
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_final
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_open
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_close
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_loadConfig
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CONFIG_PTR	pConfig
);

FTM_RET	FTDM_DBIF_NODE_initTable
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_BOOL	FTDM_DBIF_NODE_isTableExist
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_getTableCount
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_ULONG_PTR	pulCount
);

FTM_RET FTDM_DBIF_getTableList
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR _PTR_	pTables,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_NODE_count
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_ULONG_PTR	pCount
);

FTM_RET	FTDM_DBIF_NODE_getList
(
	FTM_NODE_PTR	pInfos,
	FTM_ULONG			nMaxCount,
	FTM_ULONG_PTR		pCount
);

FTM_RET	FTDM_DBIF_deleteTable
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName
);

FTM_RET	FTDM_DBIF_TABLE_deleteAllTables
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_NODE_create
(
	FTDM_DBIF_PTR	pDBIF,
 	FTM_NODE_PTR	pInfo
);

FTM_RET	FTDM_DBIF_NODE_destroy
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pDID
);

FTM_RET	FTDM_DBIF_NODE_get
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pDID,
	FTM_NODE_PTR	pInfo
);

FTM_RET	FTDM_DBIF_NODE_setURL
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pDID,
	FTM_CHAR_PTR	pURL
);

FTM_RET	FTDM_DBIF_NODE_getURL
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pDID,
	FTM_CHAR_PTR	pBuff,
	FTM_ULONG		nBuffLen
);

FTM_RET	FTDM_DBIF_NODE_setLocation
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pDID,
	FTM_CHAR_PTR	pLocation
);

FTM_RET	FTDM_DBIF_NODE_getLocation
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pDID,
	FTM_CHAR_PTR	pBuff,
	FTM_ULONG		nBuffLen
);

FTM_RET	FTDM_DBIF_EP_initTable
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_BOOL	FTDM_DBIF_EP_isTableExist
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_EP_append
(
	FTDM_DBIF_PTR	pDBIF,
 	FTM_EP_PTR		pInfo
);

FTM_RET	FTDM_DBIF_EP_remove
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID
);

FTM_RET	FTDM_DBIF_EP_count
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_ULONG_PTR	pCount
);

FTM_RET	FTDM_DBIF_EP_isExist
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_BOOL_PTR	pbExist
);

FTM_RET	FTDM_DBIF_EP_getList
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_EP_PTR		pInfos,
	FTM_ULONG		nMaxCount,
	FTM_ULONG_PTR	pCount
);

FTM_RET	FTDM_DBIF_EP_get
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_EP_PTR		pInfo
);

FTM_RET	FTDM_DBIF_EP_set
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
 	FTM_EP_PTR		pInfo
);

FTM_RET	FTDM_DBIF_EP_setName
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_CHAR_PTR	pName,
	FTM_INT			nNameLen
);

FTM_RET	FTDM_DBIF_EP_getName
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_CHAR_PTR	pName,
	FTM_INT_PTR		pNameLen
);

FTM_RET	FTDM_DBIF_EP_setInterval
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		nInterval
);

FTM_RET	FTDM_DBIF_EP_getInterval
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG_PTR	pInterval
);

FTM_RET	FTDM_DBIF_EP_setUnit
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_CHAR_PTR	pUnit,
	FTM_INT			nUnitLen
);

FTM_RET	FTDM_DBIF_EP_getUnit
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_CHAR_PTR	pUnit,
	FTM_INT_PTR		pUnitLen
);


FTM_RET	FTDM_DBIF_EP_DATA_initTable
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID
);

FTM_RET	FTDM_DBIF_EP_DATA_append
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_EP_DATA_PTR	pData
);

FTM_RET	FTDM_DBIF_EP_DATA_info
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG_PTR	pulBeginTime,
	FTM_ULONG_PTR	pulEndTime
);

FTM_RET	FTDM_DBIF_EP_DATA_get
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		nStartIndex,
	FTM_EP_DATA_PTR	pEPData,
	FTM_ULONG		nMaxCount,
	FTM_ULONG_PTR	pCount
);

FTM_RET	FTDM_DBIF_EP_DATA_getWithTime
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		xBeginTime,
	FTM_ULONG		xEndTime,
	FTM_BOOL		bAscending,
	FTM_EP_DATA_PTR	pEPData,
	FTM_ULONG		nMaxCount,
	FTM_ULONG_PTR	pCount
);

FTM_RET	FTDM_DBIF_EP_DATA_del
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_INT			nIndex,
	FTM_ULONG		nCount
);

FTM_RET	FTDM_DBIF_EP_DATA_delWithTime
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		xBeginTime,
	FTM_ULONG		xEndTime
);

FTM_RET	FTDM_DBIF_EP_DATA_count
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG_PTR	pCount
);

FTM_RET	FTDM_DBIF_EP_DATA_countWithTime
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		xBeginTime,
	FTM_ULONG		xEndTime,
	FTM_ULONG_PTR	pCount
);

FTM_RET FTDM_DBIF_setTrace
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_BOOL		bTraceON
);

FTM_RET FTDM_DBIF_getTrace
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_BOOL_PTR	pbTranceON
);

FTM_RET	FTDM_DBIF_TRIGGER_initTable
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_TRIGGER_create
(
	FTDM_DBIF_PTR	pDBIF,
 	FTM_TRIGGER_PTR	pTrigger
);

FTM_RET	FTDM_DBIF_TRIGGER_destroy
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pID
);

FTM_RET	FTDM_DBIF_TRIGGER_count
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_ULONG_PTR	pCount
);

FTM_RET	FTDM_DBIF_TRIGGER_get
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pID,
 	FTM_TRIGGER_PTR	pTrigger
);

FTM_RET	FTDM_DBIF_TRIGGER_getList
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_TRIGGER_PTR	pTriggers, 
	FTM_ULONG		nMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_TRIGGER_set
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pID,
 	FTM_TRIGGER_PTR	pTrigger
);

FTM_RET	FTDM_DBIF_ACTION_initTable
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_ACTION_create
(
	FTDM_DBIF_PTR	pDBIF,
 	FTM_ACTION_PTR	pInfo
);

FTM_RET	FTDM_DBIF_ACTION_destroy
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pActionID
);

FTM_RET	FTDM_DBIF_ACTION_count
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_ACTION_get
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pActionID,
 	FTM_ACTION_PTR	pAction
);

FTM_RET	FTDM_DBIF_ACTION_set
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pActionID,
 	FTM_ACTION_PTR	pAction
);

FTM_RET	FTDM_DBIF_ACTION_getList
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_ACTION_PTR	pActions, 
	FTM_ULONG		nMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_RULE_initTable
(
	FTDM_DBIF_PTR	pDBIF
);

FTM_RET	FTDM_DBIF_RULE_create
(
	FTDM_DBIF_PTR	pDBIF,
 	FTM_RULE_PTR	pInfo
);

FTM_RET	FTDM_DBIF_RULE_destroy
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pRuleID
);

FTM_RET	FTDM_DBIF_RULE_count
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_RULE_get
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pRuleID,
 	FTM_RULE_PTR	pRule
);

FTM_RET	FTDM_DBIF_RULE_getList
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_RULE_PTR	pRules, 
	FTM_ULONG		nMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_RULE_set
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pRuleID,
 	FTM_RULE_PTR	pRule
);

FTM_RET	FTDM_DBIF_LOG_initTable
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName
);

FTM_RET	FTDM_DBIF_LOG_isTableExist
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_BOOL_PTR	pbExist
);

FTM_RET	FTDM_DBIF_LOG_info
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_ULONG_PTR	pulCount,
	FTM_ULONG_PTR	pulStart,
	FTM_ULONG_PTR	pulEnd
);

FTM_RET	FTDM_DBIF_LOG_append
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
 	FTM_LOG_PTR	pLog
);

FTM_RET	FTDM_DBIF_LOG_del
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulCount,
	FTM_ULONG_PTR	pulDeletedCount
);

FTM_RET	FTDM_DBIF_LOG_delWithTime
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_ULONG		ulStart,
	FTM_ULONG		ulEnd,
	FTM_ULONG_PTR	pulDeletedCount
);

FTM_RET	FTDM_DBIF_LOG_count
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_LOG_countWithTime
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_ULONG		ulStart,
	FTM_ULONG		ulEnd,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_LOG_isExist
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_UINT64		ullID,
	FTM_BOOL_PTR	pbExist
);

FTM_RET	FTDM_DBIF_LOG_getList
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_LOG_PTR		pLogs, 
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_LOG_get
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_ULONG		ulIndex,
	FTM_LOG_PTR		pLogs, 
	FTM_ULONG		nMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTDM_DBIF_LOG_getWithTime
(
	FTDM_DBIF_PTR	pDBIF,
	FTM_CHAR_PTR	pTableName,
	FTM_ULONG		ulBegin,
	FTM_ULONG		ulEnd,
	FTM_LOG_PTR		pLogs, 
	FTM_ULONG		nMaxCount,
	FTM_ULONG_PTR	pulCount
);

#endif
