#ifndef	_FTM_SERVICE_INTERFACE_MESSAGE_H_
#define	_FTM_SERVICE_INTERFACE_MESSAGE_H_

#include "ftm.h"

typedef	FTM_ULONG	FTM_SIM_TYPE, _PTR_ FTM_SIM_TYPE_PTR;

typedef	struct FTM_SIM_STRUCT
{
	FTM_ULONG   	ulReqID;
	FTM_SIM_TYPE	xType;
	FTM_ULONG   	ulLen;
}	FTM_SIM, _PTR_ FTM_SIM_PTR;

typedef	struct FTM_SIM_REQ_STRUCT
{
	FTM_ULONG   	ulReqID;
	FTM_SIM_TYPE	xType;
	FTM_ULONG   	ulLen;
}	FTM_SIM_REQ, _PTR_ FTM_SIM_REQ_PTR;

typedef	struct FTM_SIM_RESP_STRUCT
{
	FTM_ULONG   	ulReqID;
	FTM_SIM_TYPE	xType;
	FTM_ULONG   	ulLen;
	FTM_RET			xRet;
}	FTM_SIM_RESP, _PTR_ FTM_SIM_RESP_PTR;

#define	FTM_SIM_TYPE_UNKNOWN			0x00000000
#define	FTM_SIM_TYPE_CONNECTION_STATUS	0x00000001

#define	FTM_SIM_TYPE_REGISTER_SUBSCRIBE	0x00000003

#define	FTM_SIM_TYPE_NET_STAT			0x00000005

typedef struct	FTM_SIM_REQ_REGISTER_SUBSCRIBE_STRUCT
{  
	FTM_SIM_TYPE		xType;
	FTM_ULONG           ulLen;
    FTM_ULONG           ulReqID;
	FTM_CHAR            pHost[FTM_URL_LEN+1];
	FTM_USHORT          usPort;
}   FTM_SIM_REQ_REGISTER_SUBSCRIBE, _PTR_ FTM_SIM_REQ_REGISTER_SUBSCRIBE_PTR;

typedef struct FTM_SIM_RESP_REGISTER_SUBSCRIBE_STRUCT
{
	FTM_SIM_TYPE		xType;
	FTM_ULONG           ulLen;
	FTM_ULONG           ulReqID;
	FTM_RET             xRet;
}   FTM_SIM_RESP_REGISTER_SUBSCRIBE, _PTR_ FTM_SIM_RESP_REGISTER_SUBSCRIBE_PTR;

FTM_RET	FTM_SIM_destroy
(
	FTM_SIM_PTR _PTR_ ppSIM
);

FTM_RET	FTM_SIM_copy
(
	FTM_SIM_PTR	pSrc,
	FTM_SIM_PTR	_PTR_ ppDest
);

typedef	struct	FTM_SIM_NOTIFY_CONNECTION_STATUS_STRUCT
{
	FTM_SIM_TYPE	xType;
	FTM_ULONG		ulLen;
	FTM_ULONG		xSenderID;
	FTM_BOOL		bConnected;
} FTM_SIM_NOTIFY_CONNECTION_STATUS, _PTR_ FTM_SIM_NOTIFY_CONNECTION_STATUS_PTR;

FTM_RET	FTM_SIM_createConnectionStatus
(
	FTM_ULONG	ulSender,
	FTM_BOOL	bConnected,
	FTM_SIM_PTR _PTR_ ppSIM
);

typedef	struct FTM_SIM_NOTIFY_CONNECTION_STATUS_STRUCT FTM_SIM_NOTIFY_NET_STAT, _PTR_ FTM_SIM_NOTIFY_NET_STAT_PTR;

FTM_RET	FTM_SIM_createNetStat
(
	FTM_ULONG	ulSender,
	FTM_BOOL	bConnected,
	FTM_SIM_PTR _PTR_ ppSIM
);


#endif

