#ifndef	_FTM_CONFIG_H_
#define	_FTM_CONFIG_H_

#include "ftm_types.h"
#include "ftm_node.h"
#include "ftm_ep.h"
#include "ftm_time.h"
#include "ftm_value.h"
#include "cjson/cJSON.h"

typedef	struct
{
	FTM_BOOL		bNew;
	FTM_CHAR		pFileName[FTM_FILE_NAME_LEN+1];
	cJSON	_PTR_	pRoot;
	FTM_CHAR_PTR	pData;
	FTM_ULONG		ulLen;
}	FTM_CONFIG, _PTR_ FTM_CONFIG_PTR;

typedef	struct
{
	cJSON	_PTR_	pObject;
}	FTM_CONFIG_ITEM, _PTR_ FTM_CONFIG_ITEM_PTR;

FTM_RET	FTM_CONFIG_create
(
	FTM_CHAR_PTR 		pFileName, 
	FTM_CONFIG_PTR _PTR_ pConfig,
	FTM_BOOL			bNew
);

FTM_RET	FTM_CONFIG_destroy
(
	FTM_CONFIG_PTR _PTR_ pConfig
);

FTM_RET	FTM_CONFIG_init
(
	FTM_CONFIG_PTR 		pConfig, 
	FTM_CHAR_PTR 		pFileName,
	FTM_BOOL			bNew
);

FTM_RET	FTM_CONFIG_final
(
	FTM_CONFIG_PTR 		pConfig
);

FTM_RET	FTM_CONFIG_print
(
	FTM_CONFIG_PTR		pConfig
);

FTM_RET	FTM_CONFIG_getItem
(
	FTM_CONFIG_PTR 		pConfig, 
	FTM_CHAR_PTR 		pName, 
	FTM_CONFIG_ITEM_PTR pItem
);

FTM_RET	FTM_CONFIG_addItem
(
	FTM_CONFIG_PTR pConfig, 
	FTM_CHAR_PTR 	pName, 
	FTM_CONFIG_ITEM_PTR pItem
);

FTM_RET	FTM_CONFIG_LIST_getItemCount
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG_PTR pulCount
);

FTM_RET	FTM_CONFIG_LIST_getItemAt
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG 			ulIndex, 
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_LIST_deleteItemAt
(
	FTM_CONFIG_ITEM_PTR	pItem,
	FTM_ULONG			ulIndex
);

FTM_RET	FTM_CONFIG_LIST_addItem
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_LIST_addItemINT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_INT				nValue,
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_LIST_addItemUSHORT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_USHORT			usValue,
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_LIST_addItemULONG
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG			ulValue,
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_LIST_addItemFLOAT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_FLOAT			fValue,
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_LIST_addItemString
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR		pValue,
	FTM_CONFIG_ITEM_PTR pChildItem
);
	
FTM_RET	FTM_CONFIG_ITEM_create
(
	FTM_CONFIG_ITEM_PTR _PTR_ ppItem
);

FTM_RET	FTM_CONFIG_ITEM_destroy
(
	FTM_CONFIG_ITEM_PTR pItem
);

FTM_RET	FTM_CONFIG_ITEM_getChildItem
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_CONFIG_ITEM_PTR pChildItem
);

FTM_RET	FTM_CONFIG_ITEM_getItemAt
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG 			ulIndex, 
	FTM_CONFIG_ITEM_PTR pChildItem
);

/*************************************
 * get item
 *************************************/
FTM_RET	FTM_CONFIG_ITEM_getItemNumber
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_FLOAT_PTR		pfValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemBOOL
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_BOOL_PTR 		pbValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemUSHORT
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_USHORT_PTR 		pusValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemINT
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_INT_PTR 		pnValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemULONG
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_ULONG_PTR 		pulValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemFLOAT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_FLOAT_PTR 		pfValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemString
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_CHAR_PTR 		pBuff, 
	FTM_ULONG 			ulBuffLen
);

FTM_RET	FTM_CONFIG_ITEM_getItemNode
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_NODE_PTR 		pNode
);

FTM_RET	FTM_CONFIG_ITEM_getItemEP
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_EP_DATA_PTR 	pData
);

FTM_RET	FTM_CONFIG_ITEM_getItemEPData
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_EP_DATA_PTR 	pData
);

FTM_RET	FTM_CONFIG_ITEM_getItemTime
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_TIME_PTR 		pTime
);

FTM_RET	FTM_CONFIG_ITEM_getItemValue
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_VALUE_PTR 		pValue
);

FTM_RET	FTM_CONFIG_ITEM_getItemEPClass
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_EP_CLASS_PTR	pEPClass
);

FTM_RET	FTM_CONFIG_ITEM_getItemSNMP
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR		pName,
	FTM_NODE_OPT_SNMP_PTR 	pSNMP
);

FTM_RET	FTM_CONFIG_ITEM_getItemMBTCP
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR		pName,
	FTM_NODE_OPT_MODBUS_OVER_TCP_PTR pMB
);

FTM_RET	FTM_CONFIG_ITEM_getItemFINS
(
	FTM_CONFIG_ITEM_PTR 	pItem, 
	FTM_CHAR_PTR			pName,
	FTM_NODE_OPT_FINS_PTR	pFINS
);
/****************************************
 * set item
 ******************************************/
FTM_RET	FTM_CONFIG_ITEM_setItemNumber
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_FLOAT			fValue
);

FTM_RET	FTM_CONFIG_ITEM_setItemBOOL
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_BOOL  			bValue
);

FTM_RET	FTM_CONFIG_ITEM_setItemUSHORT
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_USHORT 			usValue
);

FTM_RET	FTM_CONFIG_ITEM_setItemINT
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_INT 			nValue
);

FTM_RET	FTM_CONFIG_ITEM_setItemULONG
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_ULONG 			ulValue
);

FTM_RET	FTM_CONFIG_ITEM_setItemFLOAT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_FLOAT			fValue
);

FTM_RET	FTM_CONFIG_ITEM_setItemString
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_CHAR_PTR 		pBuff 
);

FTM_RET	FTM_CONFIG_ITEM_setItemNode
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_NODE_PTR 		pNode
);

FTM_RET	FTM_CONFIG_ITEM_setItemEP
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_CHAR_PTR 		pName, 
	FTM_EP_DATA_PTR 	pData
);

FTM_RET	FTM_CONFIG_ITEM_setItemEPData
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_EP_DATA_PTR 	pData
);

FTM_RET	FTM_CONFIG_ITEM_setItemTime
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_TIME_PTR		pTime
);

FTM_RET	FTM_CONFIG_ITEM_setItemValue
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_VALUE_PTR 		pValue
);

/***************************************
 *
 ***************************************/
FTM_RET	FTM_CONFIG_ITEM_createChildItem
(
	FTM_CONFIG_ITEM_PTR	pItem,
	FTM_CHAR_PTR		pName,
	FTM_CONFIG_ITEM_PTR	pChildItem
);

FTM_RET	FTM_CONFIG_ITEM_createChildList
(
	FTM_CONFIG_ITEM_PTR	pItem,
	FTM_CHAR_PTR		pName,
	FTM_CONFIG_ITEM_PTR	pChildItem
);

FTM_RET	FTM_CONFIG_ITEM_addItemNumber
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_FLOAT			fValue
);

FTM_RET	FTM_CONFIG_ITEM_addItemBOOL
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_BOOL			bValue
);

FTM_RET	FTM_CONFIG_ITEM_addItemUSHORT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_USHORT	 		usValue
);

FTM_RET	FTM_CONFIG_ITEM_addItemINT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_INT				nValue
);

FTM_RET	FTM_CONFIG_ITEM_addItemULONG
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_ULONG			ulValue
);

FTM_RET	FTM_CONFIG_ITEM_addItemFLOAT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_FLOAT			fValue
);

FTM_RET	FTM_CONFIG_ITEM_addItemString
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_CHAR_PTR		pValue
);

FTM_RET	FTM_CONFIG_ITEM_addItemTime
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pName, 
	FTM_TIME_PTR		pTime
);

FTM_RET	FTM_CONFIG_ITEM_addItemValue
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pName, 
	FTM_VALUE_PTR 		pValue
);

FTM_RET	FTM_CONFIG_ITEM_setItemSNMP
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR		pName,
	FTM_NODE_OPT_SNMP_PTR 	pSNMP
);

FTM_RET	FTM_CONFIG_ITEM_setItemMBTCP
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR		pName,
	FTM_NODE_OPT_MODBUS_OVER_TCP_PTR pMB
);

FTM_RET	FTM_CONFIG_ITEM_setItemFINS
(
	FTM_CONFIG_ITEM_PTR 	pItem, 
	FTM_CHAR_PTR			pName,
	FTM_NODE_OPT_FINS_PTR	pFINS
);
/****************************************
 *
 ****************************************/
FTM_RET	FTM_CONFIG_ITEM_getNumber
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_FLOAT_PTR pfValue
);

FTM_RET	FTM_CONFIG_ITEM_getBOOL
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_BOOL_PTR pbValue
);

FTM_RET	FTM_CONFIG_ITEM_getUSHORT
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_USHORT_PTR pusValue
);

FTM_RET	FTM_CONFIG_ITEM_getINT
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_INT_PTR 		pnValue
);

FTM_RET	FTM_CONFIG_ITEM_getULONG
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG_PTR 		pulValue
);

FTM_RET	FTM_CONFIG_ITEM_getFLOAT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_FLOAT_PTR 		pfValue
);

FTM_RET	FTM_CONFIG_ITEM_getString
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_CHAR_PTR 		pBuff, 
	FTM_ULONG 			ulBuffLen
);

FTM_RET	FTM_CONFIG_ITEM_getTime
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_TIME_PTR 		pTime
);

FTM_RET	FTM_CONFIG_ITEM_getNode
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_NODE_PTR 		pNode
);

FTM_RET	FTM_CONFIG_ITEM_getEPData
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_EP_DATA_PTR 	pData
);

FTM_RET	FTM_CONFIG_ITEM_getValue
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_VALUE_PTR 		pValue
);

FTM_RET	FTM_CONFIG_ITEM_getEPLimit
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_EP_LIMIT_PTR 	pLimit
);

FTM_RET FTM_CONFIG_ITEM_getEPClass
(	
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_EP_CLASS_PTR 	pClass
);

FTM_RET	FTM_CONFIG_ITEM_getSNMP
(
	FTM_CONFIG_ITEM_PTR	pItem, 	
	FTM_NODE_OPT_SNMP_PTR 	pSNMP
);

FTM_RET	FTM_CONFIG_ITEM_getMBTCP
(
	FTM_CONFIG_ITEM_PTR	pItem, 	
	FTM_NODE_OPT_MODBUS_OVER_TCP_PTR 	pMB
);

FTM_RET	FTM_CONFIG_ITEM_getFINS
(
	FTM_CONFIG_ITEM_PTR	pItem, 	
	FTM_NODE_OPT_FINS_PTR	pFINS
);

/**************************************
 *
 **************************************/
FTM_RET	FTM_CONFIG_ITEM_setBOOL
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_BOOL			bValue
);

FTM_RET	FTM_CONFIG_ITEM_setUSHORT
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_USHORT			usValue
);

FTM_RET	FTM_CONFIG_ITEM_setINT
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_INT     		nValue
);

FTM_RET	FTM_CONFIG_ITEM_setULONG
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_ULONG 			ulValue
);

FTM_RET	FTM_CONFIG_ITEM_setFLOAT
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_FLOAT   		fValue
);

FTM_RET	FTM_CONFIG_ITEM_setString
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_CHAR_PTR 		pBuff
);

FTM_RET	FTM_CONFIG_ITEM_setTime
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_TIME_PTR 		pTime
);

FTM_RET	FTM_CONFIG_ITEM_setNode
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_NODE_PTR 		pNode
);

FTM_RET	FTM_CONFIG_ITEM_getEP
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_EP_PTR 			pEP
);

FTM_RET	FTM_CONFIG_ITEM_setEP
(
	FTM_CONFIG_ITEM_PTR pItem, 	
	FTM_EP_PTR 			pEP
);

FTM_RET	FTM_CONFIG_ITEM_setEPData
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_EP_DATA_PTR 	pData
);

FTM_RET	FTM_CONFIG_ITEM_setValue
(
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_VALUE_PTR 		pValue
);

FTM_RET	FTM_CONFIG_ITEM_setEPLimit
(
	FTM_CONFIG_ITEM_PTR pItem, 
	FTM_EP_LIMIT_PTR 	pLimit
);

FTM_RET FTM_CONFIG_ITEM_setEPClass
(	
	FTM_CONFIG_ITEM_PTR pItem,
	FTM_EP_CLASS_PTR 	pClass
);

FTM_RET	FTM_CONFIG_ITEM_setSNMP
(
	FTM_CONFIG_ITEM_PTR	pItem, 	
	FTM_NODE_OPT_SNMP_PTR 	pSNMP
);

FTM_RET	FTM_CONFIG_ITEM_setMBTCP
(
	FTM_CONFIG_ITEM_PTR	pItem, 	
	FTM_NODE_OPT_MODBUS_OVER_TCP_PTR 	pMB
);

FTM_RET	FTM_CONFIG_ITEM_setFINS
(
	FTM_CONFIG_ITEM_PTR	pItem, 	
	FTM_NODE_OPT_FINS_PTR	pFINS
);
#endif
