#ifndef	_FTM_LOG_H_
#define	_FTM_LOG_H_

#include "ftm_types.h"
#include "ftm_time.h"

typedef	enum	FTM_LOG_TYPE_ENUM
{
	FTM_LOG_TYPE_UNKNOWN,

	FTM_LOG_TYPE_CREATE_OBJECT,
	FTM_LOG_TYPE_CREATE_NODE,
	FTM_LOG_TYPE_CREATE_EP,
	FTM_LOG_TYPE_CREATE_EVENT,
	FTM_LOG_TYPE_CREATE_ACTION,
	FTM_LOG_TYPE_CREATE_RULE,

	FTM_LOG_TYPE_DESTROY_OBJECT,
	FTM_LOG_TYPE_DESTROY_NODE,
	FTM_LOG_TYPE_DESTROY_EP,
	FTM_LOG_TYPE_DESTROY_EVENT,
	FTM_LOG_TYPE_DESTROY_ACTION,

	FTM_LOG_TYPE_DESTROY_RULE,

	FTM_LOG_TYPE_EVENT
}	FTM_LOG_TYPE, _PTR_ FTM_LOG_TYPE_PTR;

#define	FTM_LOG_FLAG_SAVED	0x00000001

typedef	FTM_ULONG	FTM_LOG_FIELD, _PTR_ FTM_LOG_FIELD_PTR;

#define	FTM_LOG_FIELD_ID			(1 << 0)
#define	FTM_LOG_FIELD_TIME			(1 << 1)
#define	FTM_LOG_FIELD_VALUE			(1 << 2)
#define	FTM_LOG_FIELD_ALL			(0xFFFF)

typedef	enum	FTM_LOG_LEVEL
{
	FTM_LOG_LEVEL_INFO = 0,
	FTM_LOG_LEVEL_WARN = 5,
	FTM_LOG_LEVEL_ALERT= 10
}	FTM_LOG_LEVEL, _PTR_ FTM_LOG_LEVEL_PTR;

typedef	struct
{
	FTM_CHAR	pObjectID[FTM_ID_LEN+1];
	FTM_RET		xResult;
}	FTM_LOG_CREATE_OBJECT_PARAMS, _PTR_ FTM_LOG_CREATE_OBJECT_PARAMS_PTR;

typedef	struct
{
	FTM_CHAR	pObjectID[FTM_ID_LEN+1];
	FTM_RET		xResult;
}	FTM_LOG_DESTROY_OBJECT_PARAMS, _PTR_ FTM_LOG_DESTROY_OBJECT_PARAMS_PTR;

typedef	struct
{
	FTM_CHAR	pRuleID[FTM_ID_LEN+1];
	FTM_BOOL	bOccurred;
}	FTM_LOG_EVENT_PARAMS, _PTR_ FTM_LOG_EVENT_PARAMS_PTR;
	
typedef	struct FTM_LOG_ITEM_STRUCT
{
	FTM_UINT64		ullID;
	FTM_LOG_TYPE	xType;
	FTM_ULONG		ulTime;
	FTM_LOG_LEVEL	xLevel;
	FTM_ULONG		xFlags;
	union
	{
		FTM_LOG_CREATE_OBJECT_PARAMS	xCreateObject;
		FTM_LOG_DESTROY_OBJECT_PARAMS	xDestroyObject;
		FTM_LOG_EVENT_PARAMS			xEvent;
	}	xParams;
}	FTM_LOG, _PTR_ FTM_LOG_PTR;

FTM_RET	FTM_LOG_create
(
	FTM_LOG_PTR _PTR_ ppLog
);

FTM_RET	FTM_LOG_destroy
(
	FTM_LOG_PTR _PTR_ ppLog
);

FTM_RET	FTM_LOG_duplicate
(
	FTM_LOG_PTR	pLog,
	FTM_LOG_PTR _PTR_ ppNewLog
);

FTM_RET	FTM_LOG_createObject
(
	FTM_CHAR_PTR	pObjectID,
	FTM_RET			xResult,
	FTM_LOG_PTR	_PTR_ ppLog
);

FTM_RET	FTM_LOG_destroyObject
(
	FTM_CHAR_PTR	pObjectID,
	FTM_RET			xResult,
	FTM_LOG_PTR	_PTR_ ppLog
);

FTM_RET	FTM_LOG_createEvent
(
	FTM_CHAR_PTR	pObjectID,
	FTM_BOOL		bOccurred,
	FTM_LOG_PTR	_PTR_ ppLog
);

FTM_CHAR_PTR	FTM_LOG_print
(
	FTM_LOG_PTR	pLog
);

#endif
