#ifndef	_FTOM_CLOUD_CLIENT_H_
#define	_FTOM_CLOUD_CLIENT_H_


#include "ftom.h"
#include "ftom_client.h"

typedef	FTM_VOID _PTR_	FTOM_CLOUD_CLIENT_PTR;

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CREATE)
(
	FTM_CHAR_PTR	pName,
	FTOM_CLOUD_CLIENT_PTR _PTR_ ppClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_DESTROY)
(
	FTOM_CLOUD_CLIENT_PTR _PTR_ ppClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_INIT)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_FINAL)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_START)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_STOP)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_IS_RUNNING)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_BOOL_PTR			pIsRunning
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_WAITING_FOR_FINISHED)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CONFIG_LOAD)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CONFIG_PTR			pConfig
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CONFIG_SAVE)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CONFIG_PTR			pConfig
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CONFIG_SHOW)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);


typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_SET_NOTIFY_CB)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTOM_CLIENT_NOTIFY_CB	fNotifyCB,
	FTM_VOID_PTR			pData
);

typedef	FTM_RET (*FTOM_CLOUD_CLIENT_MESSAGE_SEND)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTOM_MSG_PTR			pBaseMsg
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_MESSAGE_PROCESS)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTOM_MSG_PTR			pmsg
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_CONNECT)
(
	FTOM_CLOUD_CLIENT_PTR	pClient
);


typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_TRACE)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_BOOL				bTraceON
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_GATEWAY_UPDATE_STATUS)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_BOOL				bStatus
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_NODE_GET_COUNT)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_ULONG_PTR			pulCount
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_NODE_REGISTER)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_NODE_PTR			pNode
);
	
typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_NODE_UPDATE_STATUS)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CHAR_PTR			pID,
	FTM_BOOL				bStatus
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_NODE_IS_EXIST)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CHAR_PTR			pID
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_EP_GET_COUNT)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_ULONG_PTR			pulCount
);

typedef	FTM_RET	 (*FTOM_CLOUD_CLIENT_EP_GET_EPID_AT)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_ULONG				ulIndex,
	FTM_CHAR_PTR			pBuff,
	FTM_ULONG				ulBuffLen
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_EP_REGISTER)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_EP_PTR			pEP
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_EP_IS_EXIST)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CHAR_PTR			pEPID
);
	
typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_EP_UPDATE_STATUS)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CHAR_PTR			pEPID,
	FTM_BOOL				bStatus
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_EP_DATA_GET_LAST_TIME)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CHAR_PTR			pEPID,
	FTM_ULONG_PTR			pulLastTime
);

typedef	FTM_RET	(*FTOM_CLOUD_CLIENT_EP_DATA_SEND)
(
	FTOM_CLOUD_CLIENT_PTR	pClient,
	FTM_CHAR_PTR			pEPID,
	FTM_EP_DATA_PTR			pDatas,
	FTM_ULONG				ulCount
);

typedef	struct
{
	FTM_CHAR_PTR	pName;

	struct
	{
		FTM_BOOL			bServerSync;	
	}	xFlags;

	FTOM_CLOUD_CLIENT_CREATE	fCreate;
	FTOM_CLOUD_CLIENT_DESTROY	fDestroy;
	FTOM_CLOUD_CLIENT_INIT		fInit;
	FTOM_CLOUD_CLIENT_FINAL		fFinal;
	FTOM_CLOUD_CLIENT_START		fStart;
	FTOM_CLOUD_CLIENT_STOP		fStop;
	FTOM_CLOUD_CLIENT_IS_RUNNING	fIsRunning;
	FTOM_CLOUD_CLIENT_WAITING_FOR_FINISHED	fWaitingForFinished;
	FTOM_CLOUD_CLIENT_CONFIG_LOAD	fConfigLoad;
	FTOM_CLOUD_CLIENT_CONFIG_SAVE	fConfigSave;
	FTOM_CLOUD_CLIENT_CONFIG_SHOW	fConfigShow;
	FTOM_CLOUD_CLIENT_SET_NOTIFY_CB	fSetNotifyCB;
	FTOM_CLOUD_CLIENT_MESSAGE_SEND	fMessageSend;
	FTOM_CLOUD_CLIENT_MESSAGE_PROCESS	fMessageProcess;

	struct
	{
		FTOM_CLOUD_CLIENT_GATEWAY_UPDATE_STATUS	fUpdateStatus;
	}	xGateway;

	struct
	{
		FTOM_CLOUD_CLIENT_NODE_GET_COUNT		fGetCount;
		FTOM_CLOUD_CLIENT_NODE_REGISTER			fRegister;
		FTOM_CLOUD_CLIENT_NODE_IS_EXIST			fIsExist;
		FTOM_CLOUD_CLIENT_NODE_UPDATE_STATUS	fUpdateStatus;
	}	xNode;

	struct
	{
		FTOM_CLOUD_CLIENT_EP_GET_COUNT			fGetCount;
		FTOM_CLOUD_CLIENT_EP_GET_EPID_AT		fGetEPIDAt;
		FTOM_CLOUD_CLIENT_EP_REGISTER			fRegister;
		FTOM_CLOUD_CLIENT_EP_IS_EXIST			fIsExist;
		FTOM_CLOUD_CLIENT_EP_UPDATE_STATUS		fUpdateStatus;
		struct
		{
			FTOM_CLOUD_CLIENT_EP_DATA_GET_LAST_TIME	fGetLastTime;
			FTOM_CLOUD_CLIENT_EP_DATA_SEND			fSend;
		}	xData;
	}	xEP;
}	FTOM_CLOUD_CLIENT_MODULE, _PTR_ FTOM_CLOUD_CLIENT_MODULE_PTR;

FTM_RET	FTOM_CLOUD_CLIENT_getModule
(
	FTM_CHAR_PTR	pModule,
	FTOM_CLOUD_CLIENT_MODULE_PTR _PTR_ ppModule
);

#endif

