#ifndef	__FTDM_PARAMS_H__
#define	__FTDM_PARAMS_H__

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
}	FTDM_REQ_PARAMS, _PTR_ FTDM_REQ_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
}	FTDM_RESP_PARAMS, _PTR_ FTDM_RESP_PARAMS_PTR;

typedef	struct 
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_DEVICE_INFO	xInfo;
}	FTDM_REQ_CREATE_DEVICE_PARAMS,	_PTR_ FTDM_REQ_CREATE_DEVICE_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
}	FTDM_RESP_CREATE_DEVICE_PARAMS, _PTR_ FTDM_RESP_CREATE_DEVICE_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_BYTE			pDID[FTDM_DEVICE_ID_LEN];
}	FTDM_REQ_DESTROY_DEVICE_PARAMS, _PTR_ FTDM_REQ_DESTROY_DEVICE_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
}	FTDM_RESP_DESTROY_DEVICE_PARAMS, _PTR_	FTDM_RESP_DESTROY_DEVICE_PARAMS_PTR;

typedef struct	
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_BYTE			pDID[FTDM_DEVICE_ID_LEN];
}	FTDM_REQ_GET_DEVICE_INFO_PARAMS, _PTR_ 	FTDM_REQ_GET_DEVICE_INFO_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
	FTDM_DEVICE_INFO	xInfo;
}	FTDM_RESP_GET_DEVICE_INFO_PARAMS, _PTR_ FTDM_RESP_GET_DEVICE_INFO_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_BYTE			pDID[FTDM_DEVICE_ID_LEN];
}	FTDM_REQ_GET_DEVICE_TYPE_PARAMS, _PTR_	FTDM_REQ_GET_DEVICE_TYPE_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
	FTDM_DEVICE_TYPE	xType;
}	FTDM_RESP_GET_DEVICE_TYPE_PARAMS, _PTR_	FTDM_RESP_GET_DEVICE_TYPE_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_BYTE			pDID[FTDM_DEVICE_ID_LEN];
}	FTDM_REQ_GET_DEVICE_URL_PARAMS, _PTR_	FTDM_REQ_GET_DEVICE_URL_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
	FTDM_INT 			nURLLen;
	FTDM_CHAR			pURL[]; 
}	FTDM_RESP_GET_DEVICE_URL_PARAMS, _PTR_	FTDM_RESP_GET_DEVICE_URL_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_BYTE			pDID[FTDM_DEVICE_ID_LEN];
	FTDM_INT			nURLLen;
	FTDM_CHAR			pURL[];
}	FTDM_REQ_SET_DEVICE_URL_PARAMS, _PTR_ FTDM_REQ_SET_DEVICE_URL_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
}	FTDM_RESP_SET_DEVICE_URL_PARAMS, _PTR_	FTDM_RESP_SET_DEVICE_URL_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_BYTE			pDID[FTDM_DEVICE_ID_LEN];
}	FTDM_REQ_GET_DEVICE_LOCATION_PARAMS, _PTR_	FTDM_REQ_GET_DEVICE_LOCATION_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
	FTDM_INT 			nLocationLen;
	FTDM_CHAR			pLocation[]; 
}	FTDM_RESP_GET_DEVICE_LOCATION_PARAMS, _PTR_	FTDM_RESP_GET_DEVICE_LOCATION_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_BYTE			pDID[FTDM_DEVICE_ID_LEN];
	FTDM_INT			nLocationLen;
	FTDM_CHAR			pLocation[];
}	FTDM_REQ_SET_PDEVICE_LOCATION_ARAMS, _PTR_	FTDM_REQ_SET_PDEVICE_LOCATION_ARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
}	FTDM_RESP_SET_DEVICE_LOCATION_PARAMS, _PTR_	FTDM_RESP_SET_DEVICE_LOCATION_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_EP_INFO     	xInfo;
}	FTDM_REQ_CREATE_EP_PARAMS, _PTR_ FTDM_REQ_CREATE_EP_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
}	FTDM_RESP_CREATE_EP_PARAMS, _PTR_	FTDM_RESP_CREATE_EP_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_EP_ID 			xEPID;
}	FTDM_REQ_DESTROY_EP_PARAMS, _PTR_	FTDM_REQ_DESTROY_EP_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
}	FTDM_RESP_DESTROY_EP_PARAMS, _PTR_ 	FTDM_RESP_DESTROY_EP_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_EP_ID			xEPID;
}	FTDM_REQ_GET_EP_INFO_PARAMS, _PTR_ 	FTDM_REQ_GET_EP_INFO_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
	FTDM_EP_INFO		xInfo;
}	FTDM_RESP_GET_EP_INFO_PARAMS, _PTR_	FTDM_RESP_GET_EP_INFO_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_EP_ID 			xEPID; 
	FTDM_ULONG			nTime;
	FTDM_ULONG 			nValue;
}	FTDM_REQ_APPEND_EP_DATA_PARAMS, _PTR_ FTDM_REQ_APPEND_EP_DATA_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
}	FTDM_RESP_APPEND_EP_DATA_PARAMS, _PTR_	FTDM_RESP_APPEND_EP_DATA_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_EP_ID 			xEPID; 
	FTDM_ULONG 			nBeginTime; 
	FTDM_ULONG 			nEndTime; 
	FTDM_ULONG			nCount; 
}	FTDM_REQ_GET_EP_DATA_PARAMS, _PTR_	FTDM_REQ_GET_EP_DATA_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
	FTDM_ULONG			nCount; 
	FTDM_EP_DATA 		pData[];
}	FTDM_RESP_GET_EP_DATA_PARAMS, _PTR_ FTDM_RESP_GET_EP_DATA_PARAMS_PTR;

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_EP_ID 			xEPID;
	FTDM_ULONG 			nBeginTime;
	FTDM_ULONG 			nEndTime; 
	FTDM_ULONG			nCount;
}	FTDM_REQ_REMOVE_EP_DATA_PARAMS, _PTR_ FTDM_REQ_REMOVE_EP_DATA_PARAMS_PTR; 

typedef	struct
{
	FTDM_CMD			xCmd;
	FTDM_ULONG			nLen;
	FTDM_RET			nRet;
}	FTDM_RESP_REMOVE_EP_DATA_PARAMS, _PTR_ 	FTDM_RESP_REMOVE_EP_DATA_PARAMS_PTR;

#endif
