#ifndef	_FTDM_RULE_H_
#define	_FTDM_RULE_H_

#include "ftm.h"

FTM_RET	FTDM_RULE_init(FTM_VOID);
FTM_RET FTDM_RULE_final(FTM_VOID);
FTM_RET	FTDM_RULE_showList(FTM_VOID);
FTM_RET	FTDM_RULE_loadFromFile(FTM_CHAR_PTR pFileName);
FTM_RET	FTDM_RULE_loadFromDB(FTM_VOID);
FTM_RET	FTDM_RULE_add(FTM_RULE_PTR pInfo);
FTM_RET	FTDM_RULE_del(FTM_RULE_ID xID);
FTM_RET	FTDM_RULE_count(FTM_ULONG_PTR	pnCount);
FTM_RET	FTDM_RULE_get(FTM_RULE_ID xID, FTM_RULE_PTR _PTR_ 	ppRule);
FTM_RET	FTDM_RULE_getAt(FTM_ULONG	nIndex, FTM_RULE_PTR _PTR_	ppRule);

#endif
