#ifndef	__FTDM_TRACE_MODULES_H__
#define	__FTDM_TRACE_MODULES_H__

#define	FTDM_TRACE_MODULE_FTDM		40
#define	FTDM_TRACE_MODULE_DBIF		41
#define	FTDM_TRACE_MODULE_SERVER	42
#define	FTDM_TRACE_MODULE_EP		43

#endif
