#ifndef	_FTDM_ACTION_H_
#define	_FTDM_ACTION_H_

#include "ftm.h"

FTM_RET	FTDM_ACTION_init(FTM_VOID);
FTM_RET FTDM_ACTION_final(FTM_VOID);
FTM_RET	FTDM_ACTION_showList(FTM_VOID);
FTM_RET	FTDM_ACTION_loadFromFile(FTM_CHAR_PTR pFileName);
FTM_RET	FTDM_ACTION_loadFromDB(FTM_VOID);
FTM_RET	FTDM_ACTION_add(FTM_ACTION_PTR pInfo);
FTM_RET	FTDM_ACTION_del(FTM_EP_ID	xEPID);
FTM_RET	FTDM_ACTION_count(FTM_ULONG_PTR	pnCount);
FTM_RET	FTDM_ACTION_get(FTM_EP_ID	xEPID, FTM_ACTION_PTR _PTR_ 	ppEPInfo);
FTM_RET	FTDM_ACTION_getAt(FTM_ULONG	nIndex, FTM_ACTION_PTR _PTR_	ppEPInfo);

#endif
