#ifndef	__FTDM_SERVER_H__
#define	__FTDM_SERVER_H__

FTM_RET	FTDMS_service
(
	FTDM_REQ_PARAMS_PTR		pReq,
	FTDM_RESP_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_appendNodeInfo
(
	FTDM_REQ_APPEND_NODE_INFO_PARAMS_PTR	pReq,
	FTDM_RESP_APPEND_NODE_INFO_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_removeNodeInfo
(
	FTDM_REQ_REMOVE_NODE_INFO_PARAMS_PTR	pReq,
	FTDM_RESP_REMOVE_NODE_INFO_PARAMS_PTR	presp
);

FTM_RET	FTDMS_getNodeInfoCount
(
 	FTDM_REQ_GET_NODE_INFO_COUNT_PARAMS_PTR		pReq,
	FTDM_RESP_GET_NODE_INFO_COUNT_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getNodeInfo
(
 	FTDM_REQ_GET_NODE_INFO_PARAMS_PTR		pReq,
	FTDM_RESP_GET_NODE_INFO_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getNodeInfoByIndex
(
 	FTDM_REQ_GET_NODE_INFO_BY_INDEX_PARAMS_PTR	pReq,
	FTDM_RESP_GET_NODE_INFO_BY_INDEX_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getNodeType
(
 	FTDM_REQ_GET_NODE_TYPE_PARAMS_PTR		pReq,
	FTDM_RESP_GET_NODE_TYPE_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getNodeURL
(
	FTDM_REQ_GET_NODE_URL_PARAMS_PTR	pReq,
	FTDM_RESP_GET_NODE_URL_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_setNodeURL
(
 	FTDM_REQ_SET_NODE_URL_PARAMS_PTR 	pReq,
	FTDM_RESP_SET_NODE_URL_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getNodeLocation
(
 	FTDM_REQ_GET_NODE_LOCATION_PARAMS_PTR	pReq,
	FTDM_RESP_GET_NODE_LOCATION_PARAMS_PTR pResp
);

FTM_RET	FTDMS_setNodeLocation
(
 	FTDM_REQ_SET_NODE_LOCATION_PARAMS_PTR		pReq,
 	FTDM_RESP_SET_NODE_LOCATION_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_appendEPInfo
(
 	FTDM_REQ_APPEND_EP_INFO_PARAMS_PTR	pReq,
	FTDM_RESP_APPEND_EP_INFO_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_removeEPInfo
(
 	FTDM_REQ_REMOVE_EP_INFO_PARAMS_PTR	pReq,
	FTDM_RESP_REMOVE_EP_INFO_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getEPInfoCount
(
 	FTDM_REQ_GET_EP_INFO_COUNT_PARAMS_PTR	pReq,
	FTDM_RESP_GET_EP_INFO_COUNT_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getEPInfo
(
 	FTDM_REQ_GET_EP_INFO_PARAMS_PTR		pReq,
	FTDM_RESP_GET_EP_INFO_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getEPInfoByIndex
(
 	FTDM_REQ_GET_EP_INFO_BY_INDEX_PARAMS_PTR	pReq,
	FTDM_RESP_GET_EP_INFO_BY_INDEX_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_appendEPData
(
 	FTDM_REQ_APPEND_EP_DATA_PARAMS_PTR	pReq,
	FTDM_RESP_APPEND_EP_DATA_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getEPData
(
 	FTDM_REQ_GET_EP_DATA_PARAMS_PTR		pReq,
	FTDM_RESP_GET_EP_DATA_PARAMS_PTR	pResp
);

FTM_RET	FTDMS_getEPDataWithTime
(
 	FTDM_REQ_GET_EP_DATA_WITH_TIME_PARAMS_PTR		pReq,
	FTDM_RESP_GET_EP_DATA_WITH_TIME_PARAMS_PTR	pResp
);

FTM_RET 	FTDMS_removeEPData
(
 	FTDM_REQ_REMOVE_EP_DATA_PARAMS_PTR		pReq,
	FTDM_RESP_REMOVE_EP_DATA_PARAMS_PTR	pResp
);

FTM_RET 	FTDMS_removeEPDataWithTime
(
 	FTDM_REQ_REMOVE_EP_DATA_WITH_TIME_PARAMS_PTR	pReq,
	FTDM_RESP_REMOVE_EP_DATA_WITH_TIME_PARAMS_PTR	pResp
);

FTM_RET 	FTDMS_getEPDataCount
(
 	FTDM_REQ_GET_EP_DATA_COUNT_PARAMS_PTR		pReq,
	FTDM_RESP_GET_EP_DATA_COUNT_PARAMS_PTR	pResp
);

FTM_RET 	FTDMS_getEPDataCountWithTime
(
 	FTDM_REQ_GET_EP_DATA_COUNT_WITH_TIME_PARAMS_PTR	pReq,
	FTDM_RESP_GET_EP_DATA_COUNT_WITH_TIME_PARAMS_PTR	pResp
);

#endif
