#ifndef	__FTDM_SERVER_H__
#define	__FTDM_SERVER_H__

FTDM_RET	FTDMS_service
(
	FTDM_REQ_PARAMS_PTR		pReq,
	FTDM_RESP_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_createDevice
(
	FTDM_REQ_CREATE_DEVICE_PARAMS_PTR	pReq,
	FTDM_RESP_CREATE_DEVICE_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_destroyDevice
(
 	FTDM_REQ_DESTROY_DEVICE_PARAMS_PTR	pReq,
	FTDM_RESP_DESTROY_DEVICE_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getDeviceCount
(
 	FTDM_REQ_GET_DEVICE_COUNT_PARAMS_PTR		pReq,
	FTDM_RESP_GET_DEVICE_COUNT_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getDeviceInfo
(
 	FTDM_REQ_GET_DEVICE_INFO_PARAMS_PTR		pReq,
	FTDM_RESP_GET_DEVICE_INFO_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getDeviceInfoByIndex
(
 	FTDM_REQ_GET_DEVICE_INFO_BY_INDEX_PARAMS_PTR	pReq,
	FTDM_RESP_GET_DEVICE_INFO_BY_INDEX_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getDeviceType
(
 	FTDM_REQ_GET_DEVICE_TYPE_PARAMS_PTR		pReq,
	FTDM_RESP_GET_DEVICE_TYPE_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getDeviceURL
(
	FTDM_REQ_GET_DEVICE_URL_PARAMS_PTR	pReq,
	FTDM_RESP_GET_DEVICE_URL_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_setDeviceURL
(
 	FTDM_REQ_SET_DEVICE_URL_PARAMS_PTR 	pReq,
	FTDM_RESP_SET_DEVICE_URL_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getDeviceLocation
(
 	FTDM_REQ_GET_DEVICE_LOCATION_PARAMS_PTR	pReq,
	FTDM_RESP_GET_DEVICE_LOCATION_PARAMS_PTR pResp
);

FTDM_RET	FTDMS_setDeviceLocation
(
 	FTDM_REQ_SET_DEVICE_LOCATION_PARAMS_PTR		pReq,
 	FTDM_RESP_SET_DEVICE_LOCATION_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_createEP
(
 	FTDM_REQ_CREATE_EP_PARAMS_PTR	pReq,
	FTDM_RESP_CREATE_EP_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_destroyEP
(
 	FTDM_REQ_DESTROY_EP_PARAMS_PTR	pReq,
	FTDM_RESP_DESTROY_EP_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getEPCount
(
 	FTDM_REQ_GET_EP_COUNT_PARAMS_PTR	pReq,
	FTDM_RESP_GET_EP_COUNT_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getEPInfo
(
 	FTDM_REQ_GET_EP_INFO_PARAMS_PTR		pReq,
	FTDM_RESP_GET_EP_INFO_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getEPInfoByIndex
(
 	FTDM_REQ_GET_EP_INFO_BY_INDEX_PARAMS_PTR	pReq,
	FTDM_RESP_GET_EP_INFO_BY_INDEX_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_appendEPData
(
 	FTDM_REQ_APPEND_EP_DATA_PARAMS_PTR	pReq,
	FTDM_RESP_APPEND_EP_DATA_PARAMS_PTR	pResp
);

FTDM_RET	FTDMS_getEPData
(
 	FTDM_REQ_GET_EP_DATA_PARAMS_PTR		pReq,
	FTDM_RESP_GET_EP_DATA_PARAMS_PTR	pResp
);

FTDM_RET 	FTDMS_removeEPData
(
 	FTDM_REQ_REMOVE_EP_DATA_PARAMS_PTR		pReq,
	FTDM_RESP_REMOVE_EP_DATA_PARAMS_PTR	pResp
);

#endif
