#ifndef	__SQLITE_IF_H__
#define	__SQLITE_IF_H__

FTM_RET	FTDM_DBIF_init
(
	FTDM_CFG_DB_PTR	pConfig
);

FTM_RET	FTDM_DBIF_final
(
	void
);

FTM_RET	FTDM_DBIF_NODE_INFO_initTable
(
	void
);

FTM_RET	FTDM_DBIF_NODE_INFO_count
(
	FTM_ULONG_PTR		pCount
);

FTM_RET	FTDM_DBIF_NODE_INFO_getList
(
	FTM_NODE_INFO_PTR	pInfos,
	FTM_ULONG			nMaxCount,
	FTM_ULONG_PTR		pCount
);

FTM_RET	FTDM_DBIF_NODE_INFO_append
(
 	FTM_NODE_INFO_PTR	pInfo
);

FTM_RET	FTDM_DBIF_NODE_INFO_del
(
	FTM_CHAR_PTR		pDID
);

FTM_RET	FTDM_DBIF_NODE_INFO_get
(
	FTM_CHAR_PTR		pDID,
	FTM_NODE_INFO_PTR	pInfo
);

FTM_RET	FTDM_DBIF_NODE_INFO_setURL
(
	FTM_CHAR_PTR			pDID,
	FTM_CHAR_PTR			pURL
);

FTM_RET	FTDM_DBIF_NODE_INFO_getURL
(
	FTM_CHAR_PTR			pDID,
	FTM_CHAR_PTR			pBuff,
	FTM_ULONG				nBuffLen
);

FTM_RET	FTDM_DBIF_NODE_INFO_setLocation
(
	FTM_CHAR_PTR			pDID,
	FTM_CHAR_PTR			pLocation
);

FTM_RET	FTDM_DBIF_NODE_INFO_getLocation
(
	FTM_CHAR_PTR			pDID,
	FTM_CHAR_PTR			pBuff,
	FTM_ULONG				nBuffLen
);

FTM_RET	FTDM_DBIF_EP_INFO_initTable
(
	void
);

FTM_RET	FTDM_DBIF_EP_INFO_append
(
 	FTM_EP_INFO_PTR		pInfo
);

FTM_RET	FTDM_DBIF_EP_INFO_del
(
	FTM_EPID			xEPID
);

FTM_RET	FTDM_DBIF_EP_INFO_count
(
	FTM_ULONG_PTR		pCount
);

FTM_RET	FTDM_DBIF_EP_INFO_getList
(
	FTM_EP_INFO_PTR		pInfos,
	FTM_ULONG			nMaxCount,
	FTM_ULONG_PTR		pCount
);

FTM_RET	FTDM_DBIF_EP_INFO_get
(
	FTM_EPID 			xEPID, 
	FTM_EP_INFO_PTR		pInfo
);

FTM_RET	FTDM_DBIF_EP_INFO_setName
(
	FTM_EPID			xEPID,
	FTM_CHAR_PTR		pName,
	FTM_INT				nNameLen
);

FTM_RET	FTDM_DBIF_EP_INFO_getName
(
	FTM_EPID			xEPID,
	FTM_CHAR_PTR		pName,
	FTM_INT_PTR			pNameLen
);

FTM_RET	FTDM_DBIF_EP_INFO_setInterval
(
	FTM_EPID			xEPID,
	FTM_ULONG			nInterval
);

FTM_RET	FTDM_DBIF_EP_INFO_getInterval
(
	FTM_EPID			xEPID,
	FTM_ULONG_PTR		pInterval
);

FTM_RET	FTDM_DBIF_EP_INFO_setUnit
(
	FTM_EPID			xEPID,
	FTM_CHAR_PTR		pUnit,
	FTM_INT				nUnitLen
);

FTM_RET	FTDM_DBIF_EP_INFO_getUnit
(
	FTM_EPID			xEPID,
	FTM_CHAR_PTR		pUnit,
	FTM_INT_PTR			pUnitLen
);


FTM_RET	FTDM_DBIF_EP_DATA_initTable
(
	FTM_EPID			xEPID
);

FTM_RET	FTDM_DBIF_EP_DATA_append
(
	FTM_EPID			xEPID,
	FTM_EP_DATA_PTR		pData
);

FTM_RET	FTDM_DBIF_EP_DATA_info
(
	FTM_EPID			xEPID,
	FTM_ULONG_PTR		pulBeginTime,
	FTM_ULONG_PTR		pulEndTime
);

FTM_RET	FTDM_DBIF_EP_DATA_get
(
	FTM_EPID			xEPID,
	FTM_ULONG			nStartIndex,
	FTM_EP_DATA_PTR		pEPData,
	FTM_ULONG			nMaxCount,
	FTM_ULONG_PTR		pCount
);

FTM_RET	FTDM_DBIF_EP_DATA_getWithTime
(
	FTM_EPID			xEPID,
	FTM_ULONG			xBeginTime,
	FTM_ULONG			xEndTime,
	FTM_EP_DATA_PTR		pEPData,
	FTM_ULONG			nMaxCount,
	FTM_ULONG_PTR		pCount
);

FTM_RET	FTDM_DBIF_EP_DATA_del
(
	FTM_EPID			xEPID,
	FTM_ULONG			nIndex,
	FTM_ULONG			nCount
);

FTM_RET	FTDM_DBIF_EP_DATA_delWithTime
(
	FTM_EPID			xEPID,
	FTM_ULONG			xBeginTime,
	FTM_ULONG			xEndTime
);

FTM_RET	FTDM_DBIF_EP_DATA_count
(
	FTM_EPID			xEPID,
	FTM_ULONG_PTR		pCount
);

FTM_RET	FTDM_DBIF_EP_DATA_countWithTime
(
	FTM_EPID			xEPID,
	FTM_ULONG			xBeginTime,
	FTM_ULONG			xEndTime,
	FTM_ULONG_PTR		pCount
);

FTM_RET FTDM_DBIF_setTrace
(
	FTM_BOOL			bTraceON
);

FTM_RET FTDM_DBIF_getTrace
(
	FTM_BOOL_PTR		pbTranceON
);
#endif
