#ifndef	_FTM_OM_MSG_H_
#define	_FTM_OM_MSG_H_

#include "ftm.h"

#define	FTM_OM_MSG_STRING_LENGTH	1024
#define	FTM_OM_MSG_REQ_ID_LENGTH	32

typedef	FTM_ULONG	FTM_OM_MSG_ID, _PTR_ FTM_OM_MSG_ID_PTR;

typedef	enum
{
	FTM_OM_MSG_TYPE_QUIT				=	1,
	FTM_OM_MSG_TYPE_EP_CTRL				=	2,
	FTM_OM_MSG_TYPE_RULE				=	3,
	FTM_OM_MSG_TYPE_SET_EP_DATA			=	4,
	FTM_OM_MSG_TYPE_SEND_EP_DATA		=	5,
	FTM_OM_MSG_TYPE_SAVE_EP_DATA		=   6,
	FTM_OM_MSG_TYPE_PUBLISH_EP_DATA		=	7,
	FTM_OM_MSG_TYPE_TIME_SYNC			=   8,
	FTM_OM_MSG_TYPE_CONNECTED			=   9,
	FTM_OM_MSG_TYPE_DISCONNECTED		=   10,
}	FTM_OM_MSG_TYPE, _PTR_ FTM_OM_MSG_TYPE_PTR;

typedef	struct
{
	FTM_OM_MSG_TYPE	xType;
	FTM_OM_MSG_ID	xMsgID;
} FTM_OM_MSG, _PTR_ FTM_OM_MSG_PTR;

typedef struct
{
	FTM_OM_MSG_TYPE	xType;
	FTM_OM_MSG_ID	xMsgID;
	FTM_EP_ID		xEPID;
	FTM_EP_DATA		xData;
}	FTM_OM_MSG_SET_EP_DATA, _PTR_ FTM_OM_MSG_SET_EP_DATA_PTR;

typedef struct
{
	FTM_OM_MSG_TYPE	xType;
	FTM_OM_MSG_ID	xMsgID;
	FTM_EP_ID		xEPID;
	FTM_EP_DATA		xData;
}	FTM_OM_MSG_SAVE_EP_DATA, _PTR_ FTM_OM_MSG_SAVE_EP_DATA_PTR;

typedef	struct
{
	FTM_OM_MSG_TYPE	xType;
	FTM_OM_MSG_ID	xMsgID;
	FTM_EP_ID		xEPID;
	FTM_ULONG		ulCount;
	FTM_EP_DATA		pData[];
}	FTM_OM_MSG_SEND_EP_DATA, _PTR_ FTM_OM_MSG_SEND_EP_DATA_PTR;

typedef	struct
{
	FTM_OM_MSG_TYPE	xType;
	FTM_OM_MSG_ID	xMsgID;
	FTM_EP_ID		xEPID;
	FTM_ULONG		ulCount;
	FTM_EP_DATA		pData[];
}	FTM_OM_MSG_PUBLISH_EP_DATA, _PTR_ FTM_OM_MSG_PUBLISH_EP_DATA_PTR;

typedef struct
{
	FTM_OM_MSG_TYPE	xType;
	FTM_OM_MSG_ID	xMsgID;
	FTM_ULONG		ulTime;
}	FTM_OM_MSG_TIME_SYNC, _PTR_ FTM_OM_MSG_TIME_SYNC_PTR;

typedef struct
{
	FTM_OM_MSG_TYPE	xType;
	FTM_OM_MSG_ID	xMsgID;
	FTM_EP_ID		xEPID;
	FTM_EP_CTRL		xCtrl;
	FTM_ULONG		ulDuration;	
}	FTM_OM_MSG_EP_CTRL, _PTR_ FTM_OM_MSG_EP_CTRL_PTR;

typedef struct
{
	FTM_OM_MSG_TYPE	xType;
	FTM_OM_MSG_ID	xMsgID;
	FTM_RULE_ID		xRuleID;
	FTM_RULE_STATE	xRuleState;
}	FTM_OM_MSG_RULE, _PTR_ FTM_OM_MSG_RULE_PTR;

typedef struct
{
	FTM_MSG_QUEUE	xQueue;
} FTM_OM_MSG_QUEUE, _PTR_ FTM_OM_MSG_QUEUE_PTR;

FTM_RET FTM_OM_MSG_createQuit
(
	FTM_OM_MSG_PTR _PTR_ ppMsg
);

FTM_RET	FTM_OM_MSG_createSetEPData
(
	FTM_EP_ID			xEPID,
	FTM_EP_DATA_PTR		pData,
	FTM_OM_MSG_SET_EP_DATA_PTR _PTR_ ppMsg
);

FTM_RET	FTM_OM_MSG_createSaveEPData
(
	FTM_EP_ID			xEPID,
	FTM_EP_DATA_PTR		pData,
	FTM_OM_MSG_SAVE_EP_DATA_PTR _PTR_ ppMsg
);

FTM_RET	FTM_OM_MSG_createPublishEPData
(
	FTM_EP_ID			xEPID,
	FTM_EP_DATA_PTR		pData,
	FTM_ULONG			ulCount,
	FTM_OM_MSG_PUBLISH_EP_DATA_PTR _PTR_ ppMsg
);

FTM_RET	FTM_OM_MSG_createTimeSync
(
	FTM_ULONG			ulTime,
	FTM_OM_MSG_TIME_SYNC_PTR _PTR_ ppMsg
);

FTM_RET FTM_OM_MSG_createEPCtrl
(
	FTM_EP_ID			xEPID,
	FTM_EP_CTRL			xCtrl,
	FTM_ULONG			ulDuration,
	FTM_OM_MSG_EP_CTRL_PTR _PTR_ ppMsg
);

FTM_RET FTM_OM_MSG_createRule
(
	FTM_RULE_ID			xRuleID,
	FTM_RULE_STATE		xRuleState,
	FTM_OM_MSG_RULE_PTR _PTR_ ppMsg
);

FTM_RET	FTM_OM_MSG_createSendEPData
(
	FTM_EP_ID			xEPID,
	FTM_EP_DATA_PTR		pData,
	FTM_ULONG			ulCount,
	FTM_OM_MSG_SEND_EP_DATA_PTR _PTR_ ppMsg
);

FTM_RET	FTM_OM_MSG_destroy
(
	FTM_OM_MSG_PTR _PTR_ ppMsg
);

FTM_RET FTM_OM_MSGQ_create
(
	FTM_OM_MSG_QUEUE_PTR _PTR_ ppMsgQ
);

FTM_RET FTM_OM_MSGQ_destroy
(
	FTM_OM_MSG_QUEUE_PTR _PTR_ ppMsgQ
);

FTM_RET FTM_OM_MSGQ_init
(
	FTM_OM_MSG_QUEUE_PTR pMsgQ
);

FTM_RET FTM_OM_MSGQ_final
(
	FTM_OM_MSG_QUEUE_PTR pMsgQ
);

FTM_RET	FTM_OM_MSGQ_push
(
	FTM_OM_MSG_QUEUE_PTR 	pMsgQ, 
	FTM_OM_MSG_PTR 			pMsg
);

FTM_RET	FTM_OM_MSGQ_pop
(
	FTM_OM_MSG_QUEUE_PTR	pMsgQ, 
	FTM_OM_MSG_PTR _PTR_ 	ppMsg
);

FTM_RET	FTM_OM_MSGQ_timedPop
(
	FTM_OM_MSG_QUEUE_PTR 	pMsgQ, 
	FTM_ULONG 				ulTimeout, 
	FTM_OM_MSG_PTR _PTR_ 	ppMsg
);

#endif
