#ifndef	_FTM_OM_ACTION_H_
#define	_FTM_OM_ACTION_H_

#include <pthread.h>
#include "ftm.h"

typedef enum
{
	FTM_OM_ACTION_MSG_TYPE_RUN = 0
}	FTM_OM_ACTION_MSG_TYPE, _PTR_ FTM_OM_ACTION_MSG_TYPE_PTR;

typedef	struct
{
	FTM_OM_ACTION_MSG_TYPE	xType;
	FTM_ACTION_ID			xActionID;
}	FTM_OM_ACTION_MSG, _PTR_ FTM_OM_ACTION_MSG_PTR;

typedef	struct
{
	FTM_ACTION	xInfo;
	FTM_TIMER	xTimer;
}	FTM_OM_ACTION, _PTR_ FTM_OM_ACTION_PTR;

typedef	struct
{
}	FTM_OM_ACTIONM_CONFIG, _PTR_ FTM_OM_ACTIONM_CONFIG_PTR;

typedef	struct FTM_OM_ACTIONM_STRUCT
{
	FTM_OM_ACTIONM_CONFIG	xConfig;

	pthread_t			xThread;
	FTM_BOOL			bStop;

	FTM_MSG_QUEUE_PTR	pMsgQ;
	FTM_LIST_PTR		pActionList;
}	FTM_OM_ACTIONM, _PTR_ FTM_OM_ACTIONM_PTR;
	
FTM_RET	FTM_OM_ACTIONM_create(FTM_OM_ACTIONM_PTR _PTR_ ppActionM);
FTM_RET	FTM_OM_ACTIONM_destroy(FTM_OM_ACTIONM_PTR _PTR_ ppActionM);

FTM_RET	FTM_OM_ACTIONM_init(FTM_OM_ACTIONM_PTR pActionM);
FTM_RET	FTM_OM_ACTIONM_final(FTM_OM_ACTIONM_PTR pActionM);

FTM_RET	FTM_OM_ACTIONM_loadConfig(FTM_OM_ACTIONM_PTR pActionM, FTM_OM_ACTIONM_CONFIG_PTR pConfig);
FTM_RET	FTM_OM_ACTIONM_loadConfigFromFile(FTM_OM_ACTIONM_PTR pActionM, FTM_CHAR_PTR pFileName);

FTM_RET	FTM_OM_ACTIONM_start(FTM_OM_ACTIONM_PTR pActionM);
FTM_RET	FTM_OM_ACTIONM_stop(FTM_OM_ACTIONM_PTR pActionM);

FTM_RET	FTM_OM_ACTIONM_add(FTM_OM_ACTIONM_PTR pActionM, FTM_ACTION_PTR pInfo);
FTM_RET	FTM_OM_ACTIONM_del(FTM_OM_ACTIONM_PTR pActionM, FTM_ACTION_ID  xActorID);
FTM_RET	FTM_OM_ACTIONM_count(FTM_OM_ACTIONM_PTR pActionM, FTM_ULONG_PTR pulCount);
FTM_RET	FTM_OM_ACTIONM_get(FTM_OM_ACTIONM_PTR pActionM, FTM_ACTION_ID xActorID, FTM_OM_ACTION_PTR _PTR_ ppActor);
FTM_RET	FTM_OM_ACTIONM_getAt(FTM_OM_ACTIONM_PTR pActionM, FTM_ULONG ulIndex, FTM_OM_ACTION_PTR _PTR_ ppActor);

FTM_RET	FTM_OM_ACTIONM_run(FTM_OM_ACTIONM_PTR pActionM, FTM_ACTION_ID xActionID);
#endif
