#ifndef	__FTOM_PARAMS_H__
#define	__FTOM_PARAMS_H__

#include "ftom_types.h"
#include "ftom_server_cmd.h"
#include "ftom_msg.h"

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
}	FTOM_REQ_PARAMS, _PTR_ FTOM_REQ_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_PARAMS, _PTR_ FTOM_RESP_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pHost[FTM_URL_LEN+1];
	FTM_USHORT			usPort;
}	FTOM_REQ_REGISTER_SUBSCRIBE_PARAMS, _PTR_ FTOM_REQ_REGISTER_SUBSCRIBE_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_REGISTER_SUBSCRIBE_PARAMS, _PTR_ FTOM_RESP_REGISTER_SUBSCRIBE_PARAMS_PTR;

typedef	struct 
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_NODE		xNodeInfo;
}	FTOM_REQ_NODE_CREATE_PARAMS,	_PTR_ FTOM_REQ_NODE_CREATE_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_CHAR			pDID[FTM_DID_LEN + 1];
}	FTOM_RESP_NODE_CREATE_PARAMS, _PTR_ FTOM_RESP_NODE_CREATE_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
}	FTOM_REQ_NODE_DESTROY_PARAMS, _PTR_ FTOM_REQ_NODE_DESTROY_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_NODE_DESTROY_PARAMS, _PTR_ FTOM_RESP_NODE_DESTROY_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
}	FTOM_REQ_NODE_COUNT_PARAMS, _PTR_ FTOM_REQ_NODE_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_NODE_COUNT_PARAMS, _PTR_ FTOM_RESP_NODE_COUNT_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
}	FTOM_REQ_NODE_GET_PARAMS, _PTR_ FTOM_REQ_NODE_GET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_NODE		xNodeInfo;
}	FTOM_RESP_NODE_GET_PARAMS, _PTR_ FTOM_RESP_NODE_GET_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
}	FTOM_REQ_NODE_GET_AT_PARAMS, _PTR_ FTOM_REQ_NODE_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_NODE		xNodeInfo;
}	FTOM_RESP_NODE_GET_AT_PARAMS, _PTR_ FTOM_RESP_NODE_GET_AT_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
	FTM_NODE_FIELD		xFields;
	FTM_NODE			xInfo;
}	FTOM_REQ_NODE_SET_PARAMS, _PTR_ FTOM_REQ_NODE_SET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_NODE			xInfo;
}	FTOM_RESP_NODE_SET_PARAMS, _PTR_ FTOM_RESP_NODE_SET_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
}	FTOM_REQ_NODE_RUN_PARAMS, _PTR_ FTOM_REQ_NODE_RUN_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_NODE_RUN_PARAMS, _PTR_ FTOM_RESP_NODE_RUN_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
}	FTOM_REQ_NODE_STOP_PARAMS, _PTR_ FTOM_REQ_NODE_STOP_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_NODE_STOP_PARAMS, _PTR_ FTOM_RESP_NODE_STOP_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_ID_LEN+1];
}	FTOM_REQ_NODE_IS_RUN_PARAMS, _PTR_ 	FTOM_REQ_NODE_IS_RUN_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_BOOL			bRun;
}	FTOM_RESP_NODE_IS_RUN_PARAMS, _PTR_	FTOM_RESP_NODE_IS_RUN_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
}	FTOM_REQ_NODE_REGISTER_AT_SERVER_PARAMS, _PTR_ FTOM_REQ_NODE_REGISTER_AT_SERVER_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_NODE_REGISTER_AT_SERVER_PARAMS, _PTR_ FTOM_RESP_NODE_REGISTER_AT_SERVER_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
	FTM_BOOL			bRegistered;
}	FTOM_REQ_NODE_SET_SERVER_REGISTERED_PARAMS, _PTR_ FTOM_REQ_NODE_SET_SERVER_REGISTERED_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_NODE_SET_SERVER_REGISTERED_PARAMS, _PTR_ FTOM_RESP_NODE_SET_SERVER_REGISTERED_PARAMS_PTR;


typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
}	FTOM_REQ_NODE_GET_SERVER_REGISTERED_PARAMS, _PTR_ FTOM_REQ_NODE_GET_SERVER_REGISTERED_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_BOOL			bRegistered;
}	FTOM_RESP_NODE_GET_SERVER_REGISTERED_PARAMS, _PTR_ FTOM_RESP_NODE_GET_SERVER_REGISTERED_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
	FTM_ULONG			ulReportInterval;
}	FTOM_REQ_NODE_SET_REPORT_INTERVAL_PARAMS,_PTR_ FTOM_REQ_NODE_SET_REPORT_INTERVAL_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_NODE_SET_REPORT_INTERVAL_PARAMS,_PTR_ FTOM_RESP_NODE_SET_REPORT_INTERVAL_PARAMS_PTR;


/*************************************************************************
 *
 *************************************************************************/
typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EP     			xInfo;
}	FTOM_REQ_EP_CREATE_PARAMS, _PTR_ FTOM_REQ_EP_CREATE_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_EP     			xInfo;
}	FTOM_RESP_EP_CREATE_PARAMS, _PTR_	FTOM_RESP_EP_CREATE_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
}	FTOM_REQ_EP_DESTROY_PARAMS, _PTR_	FTOM_REQ_EP_DESTROY_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EP_DESTROY_PARAMS, _PTR_ 	FTOM_RESP_EP_DESTROY_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EP_TYPE			xType;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
}	FTOM_REQ_EP_COUNT_PARAMS, _PTR_ 	FTOM_REQ_EP_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			nCount;
}	FTOM_RESP_EP_COUNT_PARAMS, _PTR_	FTOM_RESP_EP_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EP_TYPE			xType;
	FTM_CHAR			pDID[FTM_DID_LEN+1];
	FTM_ULONG			ulMaxCount;
}	FTOM_REQ_EP_GET_LIST_PARAMS, _PTR_ 	FTOM_REQ_EP_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
	FTM_CHAR			pEPIDList[][FTM_EPID_LEN+1];
}	FTOM_RESP_EP_GET_LIST_PARAMS, _PTR_	FTOM_RESP_EP_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
}	FTOM_REQ_EP_GET_PARAMS, _PTR_ 	FTOM_REQ_EP_GET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_EP			xInfo;
}	FTOM_RESP_EP_GET_PARAMS, _PTR_	FTOM_RESP_EP_GET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
}	FTOM_REQ_EP_GET_AT_PARAMS, _PTR_	FTOM_REQ_EP_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_EP			xInfo;
}	FTOM_RESP_EP_GET_AT_PARAMS, _PTR_	FTOM_RESP_EP_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_ID_LEN+1];
	FTM_EP_FIELD		xFields;
	FTM_EP				xInfo;
}	FTOM_REQ_EP_SET_PARAMS, _PTR_ 	FTOM_REQ_EP_SET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EP_SET_PARAMS, _PTR_	FTOM_RESP_EP_SET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_ID_LEN+1];
}	FTOM_REQ_EP_IS_RUN_PARAMS, _PTR_ 	FTOM_REQ_EP_IS_RUN_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_BOOL			bRun;
}	FTOM_RESP_EP_IS_RUN_PARAMS, _PTR_	FTOM_RESP_EP_IS_RUN_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
}	FTOM_REQ_EP_REGISTER_AT_SERVER_PARAMS, _PTR_ FTOM_REQ_EP_REGISTER_AT_SERVER_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EP_REGISTER_AT_SERVER_PARAMS, _PTR_ FTOM_RESP_EP_REGISTER_AT_SERVER_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_ID_LEN+1];
	FTM_ULONG			ulReportInterval;
}	FTOM_REQ_EP_SET_REPORT_INTERVAL_PARAMS, _PTR_ 	FTOM_REQ_EP_SET_REPORT_INTERVAL_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EP_SET_REPORT_INTERVAL_PARAMS, _PTR_	FTOM_RESP_EP_SET_REPORT_INTERVAL_PARAMS_PTR;
typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_ID_LEN+1];
	FTM_EP_DATA			xData;
}	FTOM_REQ_EP_REMOTE_SET_PARAMS, _PTR_ 	FTOM_REQ_EP_REMOTE_SET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EP_REMOTE_SET_PARAMS, _PTR_	FTOM_RESP_EP_REMOTE_SET_PARAMS_PTR;

typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
	FTM_BOOL			bRegistered;
}	FTOM_REQ_EP_SET_SERVER_REGISTERED_PARAMS, _PTR_ FTOM_REQ_EP_SET_SERVER_REGISTERED_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EP_SET_SERVER_REGISTERED_PARAMS, _PTR_ FTOM_RESP_EP_SET_SERVER_REGISTERED_PARAMS_PTR;


typedef struct	
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
}	FTOM_REQ_EP_GET_SERVER_REGISTERED_PARAMS, _PTR_ FTOM_REQ_EP_GET_SERVER_REGISTERED_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_BOOL			bRegistered;
}	FTOM_RESP_EP_GET_SERVER_REGISTERED_PARAMS, _PTR_ FTOM_RESP_EP_GET_SERVER_REGISTERED_PARAMS_PTR;


typedef struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
}	FTOM_REQ_EP_REG_NOTIFY_RECEIVER_PARAMS, _PTR_ FTOM_REQ_EP_REG_NOTIFY_RECEIVER_PARAMS_PTR;

typedef struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EP_REG_NOTIFY_RECEIVER_PARAMS, _PTR_ FTOM_RESP_EP_REG_NOTIFY_RECEIVER_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			nLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
	FTM_EP_DATA			xData;
}	FTOM_REQ_EP_DATA_ADD_PARAMS, _PTR_ FTOM_REQ_EP_DATA_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			nLen;
	FTM_RET				xRet;
}	FTOM_RESP_EP_DATA_ADD_PARAMS, _PTR_	FTOM_RESP_EP_DATA_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
}	FTOM_REQ_EP_DATA_INFO_PARAMS, _PTR_ FTOM_REQ_EP_DATA_INFO_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulBeginTime;
	FTM_ULONG			ulEndTime;
	FTM_ULONG			ulCount;
}	FTOM_RESP_EP_DATA_INFO_PARAMS, _PTR_	FTOM_RESP_EP_DATA_INFO_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
}	FTOM_REQ_EP_DATA_GET_LAST_PARAMS, _PTR_	FTOM_REQ_EP_DATA_GET_LAST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_EP_DATA 		xData;
}	FTOM_RESP_EP_DATA_GET_LAST_PARAMS, _PTR_ FTOM_RESP_EP_DATA_GET_LAST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
	FTM_ULONG			nStartIndex;
	FTM_ULONG			nCount; 
}	FTOM_REQ_EP_DATA_GET_LIST_PARAMS, _PTR_	FTOM_REQ_EP_DATA_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_BOOL			bRemain;
	FTM_ULONG			nCount; 
	FTM_EP_DATA 		pData[];
}	FTOM_RESP_EP_DATA_GET_LIST_PARAMS, _PTR_ FTOM_RESP_EP_DATA_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
	FTM_ULONG			ulBegin;
	FTM_ULONG			ulEnd;
	FTM_BOOL			bAscending;
	FTM_ULONG			nCount; 
}	FTOM_REQ_EP_DATA_GET_LIST_WITH_TIME_PARAMS, _PTR_	FTOM_REQ_EP_DATA_GET_LIST_WITH_TIME_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_BOOL			bRemain;
	FTM_ULONG			nCount; 
	FTM_EP_DATA 		pData[];
}	FTOM_RESP_EP_DATA_GET_LIST_WITH_TIME_PARAMS, _PTR_ FTOM_RESP_EP_DATA_GET_LIST_WITH_TIME_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
	FTM_ULONG 			ulIndex; 
	FTM_ULONG			ulCount;
}	FTOM_REQ_EP_DATA_DEL_PARAMS, _PTR_ FTOM_REQ_EP_DATA_DEL_PARAMS_PTR; 

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_EP_DATA_DEL_PARAMS, _PTR_ 	FTOM_RESP_EP_DATA_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
	FTM_ULONG 			ulBegin; 
	FTM_ULONG			ulEnd;
}	FTOM_REQ_EP_DATA_DEL_WITH_TIME_PARAMS, _PTR_ FTOM_REQ_EP_DATA_DEL_WITH_TIME_PARAMS_PTR; 

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_EP_DATA_DEL_WITH_TIME_PARAMS, _PTR_ 	FTOM_RESP_EP_DATA_DEL_WITH_TIME_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
}	FTOM_REQ_EP_DATA_COUNT_PARAMS, _PTR_ FTOM_REQ_EP_DATA_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_EP_DATA_COUNT_PARAMS, _PTR_ FTOM_RESP_EP_DATA_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
	FTM_ULONG			ulStart;
	FTM_ULONG			ulEnd;
}	FTOM_REQ_EP_DATA_COUNT_WITH_TIME_PARAMS, _PTR_ FTOM_REQ_EP_DATA_COUNT_WITH_TIME_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_EP_DATA_COUNT_WITH_TIME_PARAMS, _PTR_ FTOM_RESP_EP_DATA_COUNT_WITH_TIME_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
}	FTOM_REQ_EP_DATA_TYPE_PARAMS, _PTR_ FTOM_REQ_EP_DATA_TYPE_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_VALUE_TYPE		xType;
}	FTOM_RESP_EP_DATA_TYPE_PARAMS, _PTR_ FTOM_RESP_EP_DATA_TYPE_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEPID[FTM_EPID_LEN+1];
	FTM_ULONG			ulTime;
}	FTOM_REQ_EP_DATA_SET_SERVER_TIME_PARAMS, _PTR_ FTOM_REQ_EP_DATA_SET_SERVER_TIME_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EP_DATA_SET_SERVER_TIME_PARAMS, _PTR_ FTOM_RESP_EP_DATA_SET_SERVER_TIME_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pIP[FTM_URL_LEN+1];
	FTM_USHORT			usPort;
}	FTOM_REQ_SET_NOTIFY_PARAMS, _PTR_ FTOM_REQ_SET_NOTIFY_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_SET_NOTIFY_PARAMS, _PTR_ FTOM_RESP_SET_NOTIFY_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTOM_MSG			xMsg;
}	FTOM_REQ_NOTIFY_PARAMS, _PTR_ FTOM_REQ_NOTIFY_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTOM_MSG			xMsg;
}	FTOM_RESP_NOTIFY_PARAMS, _PTR_ FTOM_RESP_NOTIFY_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_EVENT			xEvent;
}	FTOM_REQ_EVENT_ADD_PARAMS, _PTR_ FTOM_REQ_EVENT_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_CHAR			pEventID[FTM_ID_LEN+1];
}	FTOM_RESP_EVENT_ADD_PARAMS, _PTR_ FTOM_RESP_EVENT_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEventID[FTM_ID_LEN+1];
}	FTOM_REQ_EVENT_DEL_PARAMS, _PTR_ FTOM_REQ_EVENT_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EVENT_DEL_PARAMS, _PTR_ FTOM_RESP_EVENT_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
}	FTOM_REQ_EVENT_COUNT_PARAMS, _PTR_ FTOM_REQ_EVENT_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_EVENT_COUNT_PARAMS, _PTR_ FTOM_RESP_EVENT_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEventID[FTM_ID_LEN+1];
}	FTOM_REQ_EVENT_GET_PARAMS, _PTR_ FTOM_REQ_EVENT_GET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_EVENT			xEvent;
}	FTOM_RESP_EVENT_GET_PARAMS, _PTR_ FTOM_RESP_EVENT_GET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
}	FTOM_REQ_EVENT_GET_AT_PARAMS, _PTR_ FTOM_REQ_EVENT_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_EVENT			xEvent;
}	FTOM_RESP_EVENT_GET_AT_PARAMS, _PTR_ FTOM_RESP_EVENT_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pEventID[FTM_ID_LEN+1];
	FTM_EVENT_FIELD	xFields;
	FTM_EVENT			xEvent;
}	FTOM_REQ_EVENT_SET_PARAMS, _PTR_ FTOM_REQ_EVENT_SET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_EVENT_SET_PARAMS, _PTR_ FTOM_RESP_EVENT_SET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ACTION			xAction;
}	FTOM_REQ_ACTION_ADD_PARAMS, _PTR_ FTOM_REQ_ACTION_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_CHAR			pActionID[FTM_ID_LEN+1];
}	FTOM_RESP_ACTION_ADD_PARAMS, _PTR_ FTOM_RESP_ACTION_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pActionID[FTM_ID_LEN+1];
}	FTOM_REQ_ACTION_DEL_PARAMS, _PTR_ FTOM_REQ_ACTION_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_ACTION_DEL_PARAMS, _PTR_ FTOM_RESP_ACTION_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
}	FTOM_REQ_ACTION_COUNT_PARAMS, _PTR_ FTOM_REQ_ACTION_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_ACTION_COUNT_PARAMS, _PTR_ FTOM_RESP_ACTION_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pActionID[FTM_ID_LEN+1];
}	FTOM_REQ_ACTION_GET_PARAMS, _PTR_ FTOM_REQ_ACTION_GET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ACTION			xAction;
}	FTOM_RESP_ACTION_GET_PARAMS, _PTR_ FTOM_RESP_ACTION_GET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
}	FTOM_REQ_ACTION_GET_AT_PARAMS, _PTR_ FTOM_REQ_ACTION_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ACTION			xAction;
}	FTOM_RESP_ACTION_GET_AT_PARAMS, _PTR_ FTOM_RESP_ACTION_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pActionID[FTM_ID_LEN+1];
	FTM_ACTION_FIELD	xFields;
	FTM_ACTION			xAction;
}	FTOM_REQ_ACTION_SET_PARAMS, _PTR_ FTOM_REQ_ACTION_SET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_ACTION_SET_PARAMS, _PTR_ FTOM_RESP_ACTION_SET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RULE			xRule;
}	FTOM_REQ_RULE_ADD_PARAMS, _PTR_ FTOM_REQ_RULE_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_CHAR			pRuleID[FTM_ID_LEN+1];
}	FTOM_RESP_RULE_ADD_PARAMS, _PTR_ FTOM_RESP_RULE_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pRuleID[FTM_ID_LEN+1];
}	FTOM_REQ_RULE_DEL_PARAMS, _PTR_ FTOM_REQ_RULE_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_RULE_DEL_PARAMS, _PTR_ FTOM_RESP_RULE_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
}	FTOM_REQ_RULE_COUNT_PARAMS, _PTR_ FTOM_REQ_RULE_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_RULE_COUNT_PARAMS, _PTR_ FTOM_RESP_RULE_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pRuleID[FTM_ID_LEN+1];
}	FTOM_REQ_RULE_GET_PARAMS, _PTR_ FTOM_REQ_RULE_GET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_RULE			xRule;
}	FTOM_RESP_RULE_GET_PARAMS, _PTR_ FTOM_RESP_RULE_GET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
}	FTOM_REQ_RULE_GET_AT_PARAMS, _PTR_ FTOM_REQ_RULE_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_RULE			xRule;
}	FTOM_RESP_RULE_GET_AT_PARAMS, _PTR_ FTOM_RESP_RULE_GET_AT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pRuleID[FTM_ID_LEN+1];
	FTM_RULE_FIELD		xFields;
	FTM_RULE			xRule;
}	FTOM_REQ_RULE_SET_PARAMS, _PTR_ FTOM_REQ_RULE_SET_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_RULE_SET_PARAMS, _PTR_ FTOM_RESP_RULE_SET_PARAMS_PTR;


/**********************************************************************
 * Log 
 **********************************************************************/
typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
	FTM_ULONG			ulCount; 
}	FTOM_REQ_LOG_GET_LIST_PARAMS, _PTR_	FTOM_REQ_LOG_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount; 
	FTM_LOG 			pLogs[];
}	FTOM_RESP_LOG_GET_LIST_PARAMS, _PTR_ FTOM_RESP_LOG_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_REQ_LOG_COUNT_PARAMS, _PTR_ FTOM_REQ_LOG_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_LOG_COUNT_PARAMS, _PTR_ FTOM_RESP_LOG_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG 			ulIndex; 
	FTM_ULONG			ulCount;
}	FTOM_REQ_LOG_DEL_PARAMS, _PTR_ FTOM_REQ_LOG_DEL_PARAMS_PTR; 

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
}	FTOM_RESP_LOG_DEL_PARAMS, _PTR_ 	FTOM_RESP_LOG_DEL_PARAMS_PTR;

/**********************************************************************
 * Discovery
 **********************************************************************/
typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_CHAR			pIP[256];
	FTM_USHORT			usPort;
	FTM_ULONG			ulRetryCount;
}	FTOM_REQ_DISCOVERY_START_PARAMS, _PTR_ FTOM_REQ_DISCOVERY_START_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
}	FTOM_RESP_DISCOVERY_START_PARAMS, _PTR_ FTOM_RESP_DISCOVERY_START_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
}	FTOM_REQ_DISCOVERY_GET_INFO_PARAMS, _PTR_ FTOM_REQ_DISCOVERY_GET_INFO_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_BOOL			bFinished;
	FTM_ULONG			ulNodeCount;
	FTM_ULONG			ulEPCount;
}	FTOM_RESP_DISCOVERY_GET_INFO_PARAMS, _PTR_ FTOM_RESP_DISCOVERY_GET_INFO_PARAMS_PTR;


typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
	FTM_ULONG			ulCount;
}	FTOM_REQ_DISCOVERY_GET_NODE_LIST_PARAMS, _PTR_ FTOM_REQ_DISCOVERY_GET_NODE_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
	FTM_NODE			pNodeList[];
}	FTOM_RESP_DISCOVERY_GET_NODE_LIST_PARAMS, _PTR_ FTOM_RESP_DISCOVERY_GET_NODE_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_ULONG			ulIndex;
	FTM_ULONG			ulCount;
}	FTOM_REQ_DISCOVERY_GET_EP_LIST_PARAMS, _PTR_ FTOM_REQ_DISCOVERY_GET_EP_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_ULONG			ulReqID;
	FTOM_CMD			xCmd;
	FTM_ULONG			ulLen;
	FTM_RET				xRet;
	FTM_ULONG			ulCount;
	FTM_EP				pEPList[];
}	FTOM_RESP_DISCOVERY_GET_EP_LIST_PARAMS, _PTR_ FTOM_RESP_DISCOVERY_GET_EP_LIST_PARAMS_PTR;

#endif
