#ifndef	__FTOM_TRACE_MODULES_H__
#define	__FTOM_TRACE_MODULES_H__


#define	FTOM_TRACE_MODULE_NODE		10
#define	FTOM_TRACE_MODULE_EP		11
#define	FTOM_TRACE_MODULE_TRIGGER	12
#define	FTOM_TRACE_MODULE_ACTION	13
#define	FTOM_TRACE_MODULE_RULE		14

#define	FTOM_TRACE_MODULE_DMC		15

#define	FTOM_TRACE_MODULE_SNMPC		16
#define	FTOM_TRACE_MODULE_SNMPTRAP	17

#define	FTOM_TRACE_MODULE_SERVER	18

#define	FTOM_TRACE_MODULE_MQTTC		19
#define	FTOM_TRACE_MODULE_DISCOVERY	20

#define	FTOM_TRACE_MODULE_LOGGER	21



#endif
