#ifndef	_FTOM_SNMPTRAP_H_
#define	_FTOM_SNMPTRAP_H_

#include <pthread.h>
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "ftm.h"
#include "ftm_snmp.h"
#include "ftom_service.h"

#define	FTOM_SNMPTRAP_NAME_LENGTH	128
#define	FTOM_SNMPTRAP_NAME			"ftom:snmptrapd"
#define	FTOM_SNMPTRAP_PORT			162

struct FTOM_SNMPTRAP_STRUCT;

typedef	enum
{
	FTOM_SNMPTRAP_TARGET_UNKNOWN,
	FTOM_SNMPTRAP_TARGET_FT,
	FTOM_SNMPTRAP_TARGET_TPGW
}	FTOM_SNMPTRAP_TARGET, _PTR_ FTOM_SNMPTRAP_TARGET_PTR;

typedef	enum
{
	FTOM_SNMPTRAP_MSG_TYPE_UNKNOWN = 0,
	FTOM_SNMPTRAP_MSG_TYPE_EP_CHANGED,
	FTOM_SNMPTRAP_MSG_TYPE_ALERT,
	FTOM_SNMPTRAP_MSG_TYPE_DISCOVERY,
} FTOM_SNMPTRAP_MSG_TYPE, _PTR_ FTOM_SNMPTRAP_MSG_TYPE_PTR;

typedef struct
{
	FTM_CHAR				pName[FTOM_SNMPTRAP_NAME_LENGTH + 1];
	FTM_USHORT				usPort;
	FTOM_SNMPTRAP_TARGET	xTarget;
}	FTOM_SNMPTRAP_CONFIG, _PTR_ FTOM_SNMPTRAP_CONFIG_PTR;

typedef	FTM_RET (*FTOM_SNMPTRAP_CB)(struct FTOM_SNMPTRAP_STRUCT _PTR_ pSNMPTRAP, FTM_SNMP_OID_PTR pOID, FTM_CHAR_PTR pTrapMsg);

typedef	struct FTOM_SNMPTRAP_STRUCT
{
	FTOM_SNMPTRAP_CONFIG	xConfig;
	FTM_LIST			xTrapCBList;
	FTM_BOOL			bStop;
	pthread_t			xPThread;
	netsnmp_transport 	*pTransport;

	FTOM_SERVICE_ID		xServiceID;
	FTOM_SERVICE_CB		fServiceCB;
}	FTOM_SNMPTRAP, _PTR_ FTOM_SNMPTRAP_PTR;

typedef	struct
{
	FTOM_SNMPTRAP_MSG_TYPE	xMsgType;
	FTM_CHAR				pName[256];
	FTM_SNMP_OID			xOID;
	FTOM_SNMPTRAP_CB		fCB;
} 	FTOM_SNMPTRAP_TRAP_INFO, _PTR_ FTOM_SNMPTRAP_TRAP_INFO_PTR;

FTM_RET	FTOM_SNMPTRAP_create
(
	FTOM_SNMPTRAP_PTR _PTR_ ppSNMPTRAP
);

FTM_RET	FTOM_SNMPTRAP_destroy
(
	FTOM_SNMPTRAP_PTR _PTR_ ppSNMPTRAP
);

FTM_RET	FTOM_SNMPTRAP_init
(
	FTOM_SNMPTRAP_PTR pSNMPTRAP
);

FTM_RET	FTOM_SNMPTRAP_final
(
	FTOM_SNMPTRAP_PTR pSNMPTRAP
);

FTM_RET FTOM_SNMPTRAP_start
(
	FTOM_SNMPTRAP_PTR pSNMPTRAP
);

FTM_RET FTOM_SNMPTRAP_stop
(
	FTOM_SNMPTRAP_PTR pSNMPTRAP
);

FTM_RET FTOM_SNMPTRAP_loadConfig
(
	FTOM_SNMPTRAP_PTR 	pSNMPTRAP, 
	FTM_CONFIG_PTR		pConfig
);

FTM_RET FTOM_SNMPTRAP_loadConfigFromFile
(
	FTOM_SNMPTRAP_PTR 	pSNMPTRAP, 
	FTM_CHAR_PTR 		pFileName
);

FTM_RET FTOM_SNMPTRAP_saveConfig
(
	FTOM_SNMPTRAP_PTR 	pSNMPTRAP, 
	FTM_CONFIG_PTR		pConfig
);

FTM_RET FTOM_SNMPTRAP_showConfig
(
	FTOM_SNMPTRAP_PTR pSNMPTRAP
);

FTM_RET	FTOM_SNMPTRAP_setServiceCallback
(
	FTOM_SNMPTRAP_PTR 	pSNMPTRAP, 
	FTOM_SERVICE_ID 	xID, 
	FTOM_SERVICE_CB 	fServiceCB
);

FTM_RET	FTOM_SNMPTRAP_getTrapOIDCount
(
	FTOM_SNMPTRAP_PTR 		pSNMPTRAP, 
	FTM_ULONG_PTR			pulCount
);

FTM_RET	FTOM_SNMPTRAP_addTrapOID
(
	FTOM_SNMPTRAP_PTR 		pSNMPTRAP, 
	FTOM_SNMPTRAP_MSG_TYPE	xMsgType,
	FTM_CHAR_PTR			pName,
	FTM_SNMP_OID_PTR 		pOID,
	FTOM_SNMPTRAP_CB		fTrapCB
);

FTM_RET	FTOM_SNMPTRAP_getTrapOIDAt
(
	FTOM_SNMPTRAP_PTR 		pSNMPTRAP, 
	FTM_ULONG				ulIndex,
	FTOM_SNMPTRAP_TRAP_INFO_PTR 	_PTR_ 	ppTrap
);

#endif
