#ifndef	__FTOM_TRACE_MODULES_H__
#define	__FTOM_TRACE_MODULES_H__


#define	FTOM_TRACE_MODULE_FTOM		10

#define	FTOM_TRACE_MODULE_NODE		11
#define	FTOM_TRACE_MODULE_EP		12
#define	FTOM_TRACE_MODULE_TRIGGER	13
#define	FTOM_TRACE_MODULE_ACTION	14
#define	FTOM_TRACE_MODULE_RULE		15

#define	FTOM_TRACE_MODULE_DMC		16

#define	FTOM_TRACE_MODULE_SNMPC		17
#define	FTOM_TRACE_MODULE_SNMPTRAP	18

#define	FTOM_TRACE_MODULE_SERVER	19

#define	FTOM_TRACE_MODULE_MQTTC		20
#define	FTOM_TRACE_MODULE_DISCOVERY	21

#define	FTOM_TRACE_MODULE_LOGGER	22



#endif
