#ifndef	_FTOM_PLUGIN_SERVER_H_
#define	_FTOM_PLUGIN_SERVER_H_

#include "ftm.h"

FTM_RET	(*FTOM_PLUGIN_INIT)(FTM_VOID_PTR pData);
FTM_RET	(*FTOM_PLUGIN_FINAL)(FTM_VOID_PTR pData);
FTM_RET (*FTOM_PLUGIN_CREATE)(FTM_VOID_PTR _PTR_ pInstance);
FTM_RET (*FTOM_PLUGIN_START)(FTM_VOID_PTR pInstance);
FTM_RET (*FTOM_PLUGIN_STOP)(FTM_VOID_PTR pInstance);

typedef	struct
{
	FTOM_PLUGIN_INIT	fInit;
	FTOM_PLUGIN_FINAL	fFinal;
	FTOM_PLUGIN_CREATE	fCreate;
	FTOM_PLUGIN_START	fStart;
	FTOM_PLUGIN_STOP	fStop;
}	FTOM_PLUGIN_SERVER, _PTR_ FTOM_PLUGIN_SERVER_PTR;

#endif
