#ifndef	_FTOM_CONFIG_H_
#define	_FTOM_CONFIG_H_


#define	FTOM_LOOP_INTERVAL					1000000	// 1 s

#define	FTOM_DEFAULT_PACKET_SIZE			4096
#define	FTOM_DEFAULT_SERVER_SESSION_COUNT	10

#define	FTOM_DEFAULT_DISCOVERY_PORT			1234

#define	FTOM_DEFAULT_SERVER_IP				"127.0.0.1"
#define	FTOM_DEFAULT_SERVER_PORT			8888
#endif
