#ifndef	__FTOM_TRACE_MODULES_H__
#define	__FTOM_TRACE_MODULES_H__


#define	FTOM_TRACE_MODULE_NODE		8
#define	FTOM_TRACE_MODULE_EP		9
#define	FTOM_TRACE_MODULE_TRIGGER	10
#define	FTOM_TRACE_MODULE_ACTION	11
#define	FTOM_TRACE_MODULE_RULE		12

#define	FTOM_TRACE_MODULE_DMC		13

#define	FTOM_TRACE_MODULE_SNMPC		16
#define	FTOM_TRACE_MODULE_SNMPTRAP	17

#define	FTOM_TRACE_MODULE_MQTTC		18
#define	FTOM_TRACE_MODULE_DISCOVERY	19


#endif
