#ifndef	_FTOM_CONFIG_H_
#define	_FTOM_CONFIG_H_


#define	FTOM_LOOP_INTERVAL					1000 // ms
#define	FTOM_TRIGGER_LOOP_INTERVAL			1000 // ms
#define	FTOM_ACTION_LOOP_INTERVAL			1000 // ms
#define	FTOM_RULE_LOOP_INTERVAL				1000 // ms
#define	FTOM_TPCLIENT_LOOP_INTERVAL			1000 // ms
#define	FTOM_NODE_LOOP_INTERVAL				1000 // ms

#define	FTOM_DEFAULT_UPDATE_INTERVAL		10	 // s
#define	FTOM_DEFAULT_PACKET_SIZE			1500
#define	FTOM_DEFAULT_SERVER_SESSION_COUNT	10

#define	FTOM_DEFAULT_DISCOVERY_PORT			1234

#define	FTOM_DEFAULT_SERVER_IP				"127.0.0.1"
#define	FTOM_DEFAULT_SERVER_PORT			8888
#define	FTOM_DEFAULT_SERVER_TIMEOUT			5000	// ms

#define	FTOM_MAX_NODE_INTERVAL				(60 * 60 * 24)
#define	FTOM_MAX_NODE_TIMEOUT				(60 * 10)

#define	FTOM_DATA_READ_COUNT_DEFAULT		20
#define	FTOM_DATA_READ_COUNT_MAX			100
#endif
