#ifndef	__FTOM_DMC_H__
#define	__FTOM_DMC_H__

#include "ftm.h"
#include "ftdm_client.h"
#include "ftom_msg.h"
#include "ftom_service.h"

typedef	struct
{
	FTDMC_SESSION			xSession;
	FTDMC_CFG				xConfig;
	pthread_t				xThread;
	FTM_BOOL				bStop;
	FTM_BOOL				bConnected;
	FTOM_MSG_QUEUE		xMsgQ;
	FTOM_SERVICE_ID		xServiceID;
	FTOM_SERVICE_CALLBACK	fServiceCB;
}	FTOM_DMC, _PTR_	FTOM_DMC_PTR;

FTM_RET	FTOM_DMC_create
(
	FTOM_DMC_PTR _PTR_ 	ppDMC
);

FTM_RET	FTOM_DMC_destroy
(
	FTOM_DMC_PTR _PTR_ 	ppDMC
);

FTM_RET FTOM_DMC_init
(
	FTOM_DMC_PTR 	pDMC
);

FTM_RET FTOM_DMC_final
(
	FTOM_DMC_PTR pDMC
);

FTM_RET FTOM_DMC_loadFromFile
(
	FTOM_DMC_PTR 	pDMC, 
	FTM_CHAR_PTR 	pConfigFileName
);

FTM_RET	FTOM_DMC_showConfig
(
	FTOM_DMC_PTR 	pDMC
);

FTM_RET	FTOM_DMC_start
(
	FTOM_DMC_PTR 	pDMC
);

FTM_RET	FTOM_DMC_stop
(
	FTOM_DMC_PTR 	pDMC
);

FTM_RET	FTOM_DMC_isConnected
(
	FTOM_DMC_PTR 	pDMC,
	FTM_BOOL_PTR	pbConnected
);

FTM_RET	FTOM_DMC_setServiceCallback
(
	FTOM_DMC_PTR 			pDMC, 
	FTOM_SERVICE_ID 		xID, 
	FTOM_SERVICE_CALLBACK pServiceCB
);

FTM_RET	FTOM_DMC_sendMessage
(
	FTOM_DMC_PTR 	pDMC, 
	FTOM_MSG_PTR 	pMsg
);

FTM_RET	FTOM_DMC_NODE_add
(
	FTOM_DMC_PTR	pDMC,
	FTM_NODE_PTR	pInfo
);

FTM_RET	FTOM_DMC_NODE_remove
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pDID
);

FTM_RET	FTOM_DMC_NODE_count
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTOM_DMC_NODE_get
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pDID,
	FTM_NODE_PTR	pInfo
);

FTM_RET	FTOM_DMC_NODE_getAt
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG		ulIndex,
	FTM_NODE_PTR	pInfo
);

FTM_RET	FTOM_DMC_NODE_getDIDList
(
	FTOM_DMC_PTR	pDMC,
	FTM_DID_PTR		pDIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTOM_DMC_NODE_set
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pDID,
	FTM_NODE_FIELD	xFields,
	FTM_NODE_PTR	pInfo
);

FTM_RET	FTOM_DMC_EP_add
(
	FTOM_DMC_PTR 	pDMC, 
	FTM_EP_PTR 		pInfo
);

FTM_RET	FTOM_DMC_EP_remove
(
	FTOM_DMC_PTR 	pDMC, 
	FTM_CHAR_PTR	pEPID
);

FTM_RET	FTOM_DMC_EP_count
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTOM_DMC_EP_getEPIDList
(
	FTOM_DMC_PTR	pDMC,
	FTM_EPID_PTR	pEPIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTOM_DMC_EP_get
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pEPID,
	FTM_EP_PTR		pInfo
);

FTM_RET	FTOM_DMC_EP_getAt
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG		ulIndex,
	FTM_EP_PTR		pInfo
);

FTM_RET	FTOM_DMC_EP_set
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pEPID,
	FTM_EP_FIELD	xFields,
	FTM_EP_PTR		pInfo
);

FTM_RET FTOM_DMC_EP_DATA_get
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		ulStartIndex,
	FTM_EP_DATA_PTR	pData,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR 	pulCount
);

FTM_RET	FTOM_DMC_EP_DATA_add
(
	FTOM_DMC_PTR 	pDMC, 
	FTM_CHAR_PTR	pEPID,
	FTM_EP_DATA_PTR pData
);

FTM_RET	FTOM_DMC_EP_DATA_remove
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulCount,
	FTM_ULONG_PTR	pulDeletedCount
);

FTM_RET	FTOM_DMC_EP_DATA_removeWithTime
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG		ulBegin,
	FTM_ULONG		ulEnd,
	FTM_ULONG_PTR	pulDeletedCount
);

FTM_RET	FTOM_DMC_EP_DATA_count
(
	FTOM_DMC_PTR 	pDMC, 
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG_PTR 	pulCount
);

FTM_RET	FTOM_DMC_EP_DATA_info
(
	FTOM_DMC_PTR 	pDMC, 
	FTM_CHAR_PTR	pEPID,
	FTM_ULONG_PTR 	pulBeginTime, 
	FTM_ULONG_PTR 	pulEndTime, 
	FTM_ULONG_PTR 	pulCount
);

FTM_RET	FTOM_DMC_EP_CLASS_count
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG_PTR	pulCount
);


FTM_RET	FTOM_DMC_EP_CLASS_getAt
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG		ulIndex,
	FTM_EP_CLASS_PTR	pInfo
);

FTM_RET	FTOM_DMC_TRIGGER_add
(
	FTOM_DMC_PTR	pDMC,
	FTM_TRIGGER_PTR	pInfo
);

FTM_RET	FTOM_DMC_TRIGGER_remove
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pID
);

FTM_RET	FTOM_DMC_TRIGGER_count
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTOM_DMC_TRIGGER_get
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pID,
	FTM_TRIGGER_PTR	pInfo
);

FTM_RET	FTOM_DMC_TRIGGER_getAt
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG		ulIndex,
	FTM_TRIGGER_PTR	pInfo
);

FTM_RET	FTOM_DMC_TRIGGER_set
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pID,
	FTM_TRIGGER_FIELD	xFields,
	FTM_TRIGGER_PTR	pInfo
);

FTM_RET	FTOM_DMC_TRIGGER_getIDList
(
	FTOM_DMC_PTR	pDMC,
	FTM_ID_PTR		pIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTOM_DMC_ACTION_add
(
	FTOM_DMC_PTR	pDMC,
	FTM_ACTION_PTR	pInfo
);

FTM_RET	FTOM_DMC_ACTION_count
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTOM_DMC_ACTION_remove
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pID
);

FTM_RET	FTOM_DMC_ACTION_get
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pID,
	FTM_ACTION_PTR	pInfo
);

FTM_RET	FTOM_DMC_ACTION_getAt
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG		ulIndex,
	FTM_ACTION_PTR	pInfo
);

FTM_RET	FTOM_DMC_ACTION_set
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pID,
	FTM_ACTION_FIELD	xFields,
	FTM_ACTION_PTR	pInfo
);

FTM_RET	FTOM_DMC_ACTION_getIDList
(
	FTOM_DMC_PTR	pDMC,
	FTM_ID_PTR		pIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTOM_DMC_RULE_add
(
	FTOM_DMC_PTR	pDMC,
	FTM_RULE_PTR	pInfo
);

FTM_RET	FTOM_DMC_RULE_remove
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pID
);

FTM_RET	FTOM_DMC_RULE_count
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG_PTR	pulCount
);

FTM_RET	FTOM_DMC_RULE_get
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pID,
	FTM_RULE_PTR	pInfo
);

FTM_RET	FTOM_DMC_RULE_getAt
(
	FTOM_DMC_PTR	pDMC,
	FTM_ULONG		ulIndex,
	FTM_RULE_PTR	pInfo
);

FTM_RET	FTOM_DMC_RULE_set
(
	FTOM_DMC_PTR	pDMC,
	FTM_CHAR_PTR	pID,
	FTM_RULE_FIELD	xFields,
	FTM_RULE_PTR	pInfo
);

FTM_RET	FTOM_DMC_RULE_getIDList
(
	FTOM_DMC_PTR	pDMC,
	FTM_ID_PTR		pIDs,
	FTM_ULONG		ulIndex,
	FTM_ULONG		ulMaxCount,
	FTM_ULONG_PTR	pulCount
);

#endif

