#ifndef	_FTM_OM_TRIGGER_H_
#define	_FTM_OM_TRIGGER_H_

#include <pthread.h>
#include "ftm.h"

typedef	FTM_TRIGGER_ID	FTM_OM_TRIGGER_ID;

typedef	enum
{
	FTM_OM_TRIGGER_STATE_RESET,
	FTM_OM_TRIGGER_STATE_PRESET,
	FTM_OM_TRIGGER_STATE_SET,
	FTM_OM_TRIGGER_STATE_PRERESET
}	FTM_OM_TRIGGER_STATE, _PTR_ FTM_TRIGGER_STATE_PTR;

typedef	struct
{
	FTM_TRIGGER			xInfo;
	FTM_TIMER			xDetectionTimer;
	FTM_TIMER			xHoldingTimer;
	FTM_EP_DATA			xData;
	FTM_OM_TRIGGER_STATE	xState;
	FTM_TIME			xOccurrenceTime;
	FTM_TIME			xReleaseTime;
	FTM_LOCK			xLock;
}	FTM_OM_TRIGGER, _PTR_ FTM_OM_TRIGGER_PTR;

typedef	struct
{
}	FTM_OM_TRIGGERM_CONFIG, _PTR_ FTM_OM_TRIGGERM_CONFIG_PTR;

typedef	struct FTM_OM_TRIGGERM_STRUCT
{
	FTM_OM_TRIGGERM_CONFIG	xConfig;
	FTM_MSG_QUEUE_PTR	pMsgQ;
	FTM_BOOL			bStop;
	FTM_LIST			xEventList;
	pthread_t			xEventThread;
}	FTM_OM_TRIGGERM, _PTR_ FTM_OM_TRIGGERM_PTR;
	
FTM_RET	FTM_OM_TRIGGERM_create(FTM_OM_TRIGGERM_PTR _PTR_ pTriggerM);
FTM_RET	FTM_OM_TRIGGERM_destroy(FTM_OM_TRIGGERM_PTR _PTR_ pTriggerM);

FTM_RET	FTM_OM_TRIGGERM_init(FTM_OM_TRIGGERM_PTR pTriggerM);
FTM_RET	FTM_OM_TRIGGERM_final(FTM_OM_TRIGGERM_PTR pTriggerM);

FTM_RET	FTM_OM_TRIGGERM_loadConfig(FTM_OM_TRIGGERM_PTR pTriggerM, FTM_CHAR_PTR pFileName);

FTM_RET	FTM_OM_TRIGGERM_start(FTM_OM_TRIGGERM_PTR pTriggerM);
FTM_RET	FTM_OM_TRIGGERM_stop(FTM_OM_TRIGGERM_PTR pTriggerM);

FTM_RET	FTM_OM_TRIGGERM_add(FTM_OM_TRIGGERM_PTR pTriggerM, FTM_TRIGGER_PTR pEvent);
FTM_RET	FTM_OM_TRIGGERM_del(FTM_OM_TRIGGERM_PTR pTriggerM, FTM_OM_TRIGGER_ID  xEventID);
FTM_RET	FTM_OM_TRIGGERM_count(FTM_OM_TRIGGERM_PTR pTriggerM, FTM_ULONG_PTR pulCount);
FTM_RET	FTM_OM_TRIGGERM_get(FTM_OM_TRIGGERM_PTR pTriggerM, FTM_OM_TRIGGER_ID xEventID, FTM_OM_TRIGGER_PTR _PTR_ ppEvent);
FTM_RET	FTM_OM_TRIGGERM_getAt(FTM_OM_TRIGGERM_PTR pTriggerM, FTM_ULONG ulIndex, FTM_OM_TRIGGER_PTR _PTR_ ppEvent);

FTM_RET	FTM_OM_TRIGGERM_updateEP(FTM_OM_TRIGGERM_PTR pTriggerM, FTM_EP_ID xEPID, FTM_EP_DATA_PTR pData);
#endif
